# Generated by Django 2.1.13 on 2022-04-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0012_auto_20220407_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basingpoint',
            name='basing_point_code',
            field=models.CharField(db_column='BasingPointCode', default='Test', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='basingpointhistory',
            name='basing_point_code',
            field=models.CharField(db_column='BasingPointCode', default='Test', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.CharField(db_column='CityCode', default='Test', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cityhistory',
            name='city_code',
            field=models.CharField(db_column='CityCode', default='Test', max_length=10, null=True, unique=True),
        ),
    ]
