# Generated by Django 2.1.13 on 2022-06-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0015_auto_20220615_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basingpoint',
            name='province',
        ),
        migrations.RemoveField(
            model_name='basingpointhistory',
            name='province_version',
        ),
        migrations.RemoveField(
            model_name='postalcode',
            name='service_point',
        ),
        migrations.RemoveField(
            model_name='postalcodehistory',
            name='service_point_version',
        ),
        migrations.RemoveField(
            model_name='servicepoint',
            name='basing_point',
        ),
        migrations.RemoveField(
            model_name='servicepoint',
            name='province',
        ),
        migrations.RemoveField(
            model_name='servicepointhistory',
            name='basing_point_version',
        ),
        migrations.RemoveField(
            model_name='servicepointhistory',
            name='province_version',
        ),
        migrations.AddField(
            model_name='basingpointhistory',
            name='terminal_version_id',
            field=models.ForeignKey(db_column='TerminalVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.TerminalHistory'),
        ),
        migrations.AddField(
            model_name='postalcodehistory',
            name='province_version_id',
            field=models.ForeignKey(db_column='ProvinceVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.ProvinceHistory'),
        ),
        migrations.AddField(
            model_name='servicepointhistory',
            name='terminal_version_id',
            field=models.ForeignKey(db_column='TerminalVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.TerminalHistory'),
        ),
        migrations.AlterField(
            model_name='province',
            name='province_code',
            field=models.CharField(db_column='ProvinceCode', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='provincehistory',
            name='province_code',
            field=models.CharField(db_column='ProvinceCode', max_length=4),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_code',
            field=models.CharField(db_column='RegionCode', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='regionhistory',
            name='region_code',
            field=models.CharField(db_column='RegionCode', max_length=50),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='terminal_code',
            field=models.CharField(db_column='TerminalCode', max_length=10),
        ),
        migrations.AlterField(
            model_name='terminalhistory',
            name='terminal_code',
            field=models.CharField(db_column='TerminalCode', max_length=10),
        ),
    ]
