# Generated by Django 2.1.13 on 2022-06-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0016_auto_20220615_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservicelevelhistory',
            name='sub_service_level_code',
            field=models.CharField(db_column='SubServiceLevelCode', max_length=50),
        ),
    ]
