# Generated by Django 2.1.13 on 2022-06-21 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0017_auto_20220618_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='postal_code',
            field=models.ForeignKey(db_column='PostalCodeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.PostalCode'),
        ),
        migrations.AddField(
            model_name='terminalhistory',
            name='postal_code_version',
            field=models.ForeignKey(db_column='PostalCodeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.PostalCodeHistory'),
        ),
    ]
