# Generated by Django 2.1.13 on 2022-08-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0020_auto_20220705_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTreeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='Code', max_length=100)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('point_type_id', models.IntegerField(db_column='PointTypeID')),
                ('point_type_name', models.CharField(db_column='PointTypeName', max_length=100)),
                ('point_type_order_id', models.IntegerField(db_column='PointTypeOrderID')),
            ],
            options={
                'db_table': 'V_LocationTree',
                'managed': False,
            },
        ),
    ]
