# Generated by Django 2.1.13 on 2022-07-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0020_auto_20220705_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='countryhistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
    ]
