# Generated by Django 2.1.13 on 2022-07-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0021_auto_20220708_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='provincehistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='legacy_id',
            field=models.TextField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='regionhistory',
            name='legacy_id',
            field=models.TextField(blank=True, db_column='LegacyID', null=True),
        ),
    ]
