# Generated by Django 2.1.13 on 2022-07-27 17:39

from django.db import migrations, models, connection
import django.db.models.deletion


class Migration(migrations.Migration):
    def apply_circular_fk(apps, schema_editor):
        cursor_update = connection.cursor()
        apply_fk = """ALTER TABLE [dbo].[BasingPoint]  WITH NOCHECK ADD  CONSTRAINT [BasingPoint_Terminal_FK] FOREIGN KEY([DefaultTerminalID])
                      REFERENCES [dbo].[Terminal] ([TerminalID])
                      ON DELETE CASCADE """
        cursor_update.execute(apply_fk)

    dependencies = [
        ('pac', '0022_auto_20220708_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basingpoint',
            name='terminal_id',
        ),
        migrations.RemoveField(
            model_name='basingpointhistory',
            name='terminal_version_id',
        ),
        migrations.AddField(
            model_name='basingpoint',
            name='default_terminal_id',
            field=models.BigIntegerField(blank=True, db_column='DefaultTerminalID', null=True),
        ),
        migrations.AddField(
            model_name='basingpoint',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='basingpointhistory',
            name='default_terminal_version_id',
            field=models.BigIntegerField(blank=True, db_column='DefaultTerminalVersionID', null=True),
        ),
        migrations.AddField(
            model_name='basingpointhistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='basing_point_id',
            field=models.ForeignKey(db_column='BasingPointID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.BasingPoint'),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='postal_code',
            field=models.CharField(blank=True, db_column='PostalCode', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='postalcodehistory',
            name='basing_point_version_id',
            field=models.ForeignKey(db_column='BasingPointVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.BasingPointHistory'),
        ),
        migrations.AddField(
            model_name='postalcodehistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='postalcodehistory',
            name='postal_code_id',
            field=models.ForeignKey(db_column='PostalCodeID', default=1, on_delete=django.db.models.deletion.CASCADE, to='pac.PostalCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='basing_point_id',
            field=models.ForeignKey(db_column='BasingPointID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.BasingPoint'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='description',
            field=models.TextField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='servicepointhistory',
            name='basing_point_version_id',
            field=models.ForeignKey(db_column='BasingPointVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.BasingPointHistory'),
        ),
        migrations.AddField(
            model_name='servicepointhistory',
            name='description',
            field=models.TextField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicepointhistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='basing_point_id',
            field=models.ForeignKey(db_column='BasingPointID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.BasingPoint'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='terminalhistory',
            name='basing_point_version_id',
            field=models.ForeignKey(db_column='BasingPointVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.BasingPointHistory'),
        ),
        migrations.AddField(
            model_name='terminalhistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AlterField(
            model_name='basingpoint',
            name='description',
            field=models.TextField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basingpointhistory',
            name='description',
            field=models.TextField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countryhistory',
            name='description',
            field=models.TextField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postalcodehistory',
            name='postal_code',
            field=models.CharField(blank=True, db_column='PostalCode', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='description',
            field=models.TextField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provincehistory',
            name='description',
            field=models.TextField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='regionhistory',
            name='description',
            field=models.TextField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='description',
            field=models.TextField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='terminalhistory',
            name='description',
            field=models.TextField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterIndexTogether(
            name='terminal',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='city',
        ),
        migrations.RunPython(apply_circular_fk),
    ]
