# Generated by Django 2.1.13 on 2022-07-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0023_auto_20220727_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='basingpoint',
            name='province_id',
            field=models.ForeignKey(blank=True, db_column='ProvinceID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.Province'),
        ),
        migrations.AddField(
            model_name='basingpointhistory',
            name='province_version_id',
            field=models.ForeignKey(blank=True, db_column='ProvinceVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.ProvinceHistory'),
        ),
    ]
