# Generated by Django 2.1.13 on 2022-07-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0024_auto_20220727_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postalcode',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='postalcodehistory',
            name='province_version_id',
        ),
        migrations.RemoveField(
            model_name='servicepoint',
            name='terminal_id',
        ),
        migrations.RemoveField(
            model_name='servicepointhistory',
            name='terminal_version_id',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='region',
        ),
        migrations.RemoveField(
            model_name='terminalhistory',
            name='postal_code_version',
        ),
        migrations.RemoveField(
            model_name='terminalhistory',
            name='region_version',
        ),
    ]
