# Generated by Django 2.1.13 on 2022-08-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0026_auto_20220729_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelevel',
            name='service_level_code',
            field=models.CharField(db_column='ServiceLevelCode', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicelevelhistory',
            name='service_level_code',
            field=models.CharField(db_column='ServiceLevelCode', max_length=10),
        ),
        migrations.AlterField(
            model_name='subservicelevel',
            name='sub_service_level_code',
            field=models.CharField(db_column='SubServiceLevelCode', max_length=10),
        ),
        migrations.AlterField(
            model_name='subservicelevelhistory',
            name='sub_service_level_code',
            field=models.CharField(db_column='SubServiceLevelCode', max_length=10),
        ),
    ]
