# Generated by Django 2.1.13 on 2022-08-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0027_auto_20220803_0907'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subservicelevel',
            unique_together={('is_active', 'sub_service_level_code')},
        ),
    ]
