# Generated by Django 2.1.13 on 2022-08-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0028_auto_20220803_1132'),
        ('pac', '0021_locationtreeview'),
    ]

    operations = [
    ]
