# Generated by Django 2.1.13 on 2022-08-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0029_merge_20220803_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
