# Generated by Django 2.1.13 on 2022-08-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0030_auto_20220804_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepoint',
            name='default_postal_code_id',
            field=models.ForeignKey(db_column='DefaultPostalCodeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.PostalCode'),
        ),
        migrations.AddField(
            model_name='servicepointhistory',
            name='default_postal_code_version_id',
            field=models.ForeignKey(db_column='DefaultPostalCodeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.PostalCodeHistory'),
        ),
    ]
