# Generated by Django 2.1.13 on 2022-09-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0031_auto_20220811_1145'),
        ('pac', '0031_auto_20220810_1019'),
    ]

    operations = [
    ]
