# Generated by Django 2.1.13 on 2022-09-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0032_merge_20220907_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalcode',
            name='description',
            field=models.CharField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postalcodehistory',
            name='description',
            field=models.CharField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basingpoint',
            name='basing_point_name',
            field=models.CharField(db_column='BasingPointName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basingpointhistory',
            name='basing_point_name',
            field=models.CharField(db_column='BasingPointName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(db_column='CityName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cityhistory',
            name='city_name',
            field=models.CharField(db_column='CityName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(db_column='CountryName', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='countryhistory',
            name='country_name',
            field=models.CharField(db_column='CountryName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='postal_code_name',
            field=models.CharField(db_column='PostalCodeName', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postalcodehistory',
            name='postal_code_name',
            field=models.CharField(db_column='PostalCodeName', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='province_name',
            field=models.CharField(db_column='ProvinceName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='provincehistory',
            name='province_name',
            field=models.CharField(db_column='ProvinceName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(blank=True, db_column='RegionName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regionhistory',
            name='region_name',
            field=models.CharField(db_column='RegionName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='service_point_name',
            field=models.CharField(db_column='ServicePointName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicepointhistory',
            name='service_point_name',
            field=models.CharField(db_column='ServicePointName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='terminal_name',
            field=models.CharField(db_column='TerminalName', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='terminalhistory',
            name='terminal_name',
            field=models.CharField(db_column='TerminalName', max_length=40, null=True),
        ),
    ]
