# Generated by Django 2.1.13 on 2022-09-22 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0034_auto_20220909_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='service_point',
            field=models.ForeignKey(db_column='ServicePointID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.ServicePoint'),
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='service_point_version',
            field=models.ForeignKey(db_column='ServicePointVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.ServicePointHistory'),
        ),
    ]
