# Generated by Django 2.1.13 on 2022-09-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0035_auto_20220922_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='city_version',
        ),
    ]
