# Generated by Django 2.1.13 on 2022-09-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0036_auto_20220922_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='CityHistory',
        ),
    ]
