# Generated by Django 2.1.13 on 2022-05-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name_plural': 'Persona'},
        ),
        migrations.AlterModelOptions(
            name='personahistory',
            options={'verbose_name_plural': 'Persona_History'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelOptions(
            name='userhistory',
            options={'verbose_name_plural': 'User_History'},
        ),
    ]
