# Generated by Django 2.1.13 on 2020-09-15 01:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pac', '__first__'),
        ('core', '0001_initial'),
    ]

    operations = [

    ]
