# Generated by Django 2.1.13 on 2020-11-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0003_auto_20201030_2023'),
    ]

    operations = [
    ]
