# Generated by Django 2.1.13 on 2022-04-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0042_auto_20220411_1452'),
        ('rrf', '0041_merge_20220412_0938'),
    ]

    operations = [
    ]
