# Generated by Django 2.1.13 on 2022-04-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0043_merge_20220412_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zone_code',
            field=models.CharField(db_column='ZoneCode', default='Test', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='zonehistory',
            name='zone_code',
            field=models.CharField(db_column='ZoneCode', default='Test', max_length=10, null=True, unique=True),
        ),
    ]
