# Generated by Django 2.1.13 on 2022-04-14 13:17

from django.db import migrations, models, connection
import django.db.models.deletion
import datetime

def drop_acc_tables_if_exists(apps, schema_editor):
    try:
        cursor_drop_acc_tables = connection.cursor()
        sql_drop_acc_tables = """
                    DROP TABLE IF EXISTS
                    dbo.AccessorialStorage_History, dbo.AccessorialStorage,
                    dbo.AccessorialDetention_History, dbo.FreeTime_History,
                    dbo.AccessorialDetention, dbo.AccessorialHeader_History,
                    dbo.AccessorialDetail_History, dbo.AccessorialDetail, dbo.AccessorialHeader,
                    dbo.FreeTime, dbo.AccRangeType_History, dbo.AccRangeType,
                    dbo.AccFactor_History, dbo.AccFactor, dbo.AccChargeBehavior_History, dbo.AccChargeBehavior
                    ;"""
        cursor_drop_acc_tables.execute(sql_drop_acc_tables)

        #Rename History Tables with "-"
        cursor_rename_table = connection.cursor()
        sql_rename_table = """
                    IF EXISTS(SELECT name FROM sys.tables WHERE name = 'dbo.CustomerZonesHistory')
                    BEGIN
                    	IF NOT EXISTS(SELECT name FROM sys.tables WHERE name = 'dbo.CustomerZones_History')
                        BEGIN
                            EXEC sp_rename 'dbo.CustomerZonesHistory', 'dbo.CustomerZones_History';
                        END
                    END
                    """
        cursor_rename_table.execute(sql_rename_table)

        cursor_rename_table = connection.cursor()
        sql_rename_table = """
                    IF EXISTS(SELECT name FROM sys.tables WHERE name = 'dbo.SubPostalCodeHistory')
                    BEGIN
                        IF NOT EXISTS(SELECT name FROM sys.tables WHERE name = 'dbo.SubPostalCode_History')
                        BEGIN
                            EXEC sp_rename 'dbo.SubPostalCodeHistory','dbo.SubPostalCode_History';
                        END
                    END
                    """
        cursor_rename_table.execute(sql_rename_table)
    except Exception as e:
        raise e

class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0033_auto_20220405_1451'),
        ('rrf', '0036_auto_20220407_1304'),
        ('rrf', '0044_auto_20220412_1423'),
    ]

    operations = [

        #Invoke drop_acc_tables_if_exists
        migrations.RunPython(drop_acc_tables_if_exists, reverse_code=migrations.RunPython.noop),

        migrations.CreateModel(
            name='AccChargeBehavior',
            fields=[
                ('acc_charge_behavior_id', models.BigAutoField(db_column='AccChargeBehaviorID', primary_key=True, serialize=False)),
                ('tm_charge_behavior_code', models.TextField(db_column='TMChargeBehaviorCode', max_length=40, null=True, default=None)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('acc_charge_behavior', models.TextField(db_column='AccChargeBehavior', max_length=10, null=True, default=None)),
            ],
            options={
                'db_table': 'AccChargeBehavior',
            },
        ),


        migrations.CreateModel(
             name='AccChargeBehaviorHistory',
             fields=[
                 ('version_num', models.IntegerField(db_column='VersionNum', null=True, default=None)),
                 ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=False)),
                 ('updated_on', models.DateTimeField(db_column='UpdatedOn', default=None)),
                 ('updated_by', models.TextField(db_column='UpdatedBy', default=None)),
                 ('base_version', models.IntegerField(db_column='BaseVersion', default=None)),
                 ('comments', models.TextField(db_column='Comments', default=None)),
                 ('acc_charge_behavior_version_id', models.BigAutoField(db_column='AccChargeBehaviorVersionID', primary_key=True, serialize=False)),
                 ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                 ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                 ('acc_charge_behavior', models.TextField(db_column='AccChargeBehavior', max_length=10, null=True, default=None)),
                 ('tm_charge_behavior_code', models.TextField(db_column='TMChargeBehaviorCode', max_length=40, null=True, default=None)),
                 ('acc_charge_behavior_id', models.ForeignKey(db_column='AccChargeBehaviorID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccChargeBehavior')),
             ],
             options={
                 'db_table': 'AccChargeBehavior_History',
             },
        ),


        migrations.CreateModel(
            name='FreeTime',
            fields=[
                ('free_time_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='FreeTimeID')),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('tm_range_type_code', models.BigIntegerField(db_column='TMRangeTypeCode', default=None)),
                ('min_break', models.DecimalField(db_column='MinBreak', decimal_places=6, max_digits=19, null=True, default=None)),
                ('max_break', models.DecimalField(db_column='MaxBreak', decimal_places=6, max_digits=19, null=True, default=None)),
            ],
            options={
                'db_table': 'FreeTime',
            },
        ),

        migrations.CreateModel(
            name='FreeTimeHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=None)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=False)),
                ('updated_on', models.DateTimeField(db_column='UpdatedOn', default=None)),
                ('updated_by', models.TextField(db_column='UpdatedBy', default=None)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None)),
                ('comments', models.TextField(db_column='Comments', default=None)),
                ('free_time_version_id', models.BigAutoField(db_column='FreeTimeVersionID', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('min_break', models.DecimalField(db_column='MinBreak', decimal_places=6, max_digits=19, null=True, default=None)),
                ('max_break', models.DecimalField(db_column='MaxBreak', decimal_places=6, max_digits=19, null=True, default=None)),
                ('free_time_id', models.ForeignKey(db_column='FreeTimeID', on_delete=django.db.models.deletion.CASCADE, to='rrf.FreeTime', related_name='+')),
           ],

            options={
                'db_table': 'FreeTime_History',
            },
        ),

        migrations.CreateModel(
            name='AccFactor',
            fields=[
                ('acc_factor_id', models.BigAutoField(db_column='AccFactorID', primary_key=True, serialize=False)),
                ('tm_acc_factor_code', models.TextField(db_column='TMAccFactorCode', max_length=10, null=True, default=None)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('acc_factor', models.TextField(db_column='AccFactor', max_length=40, null=True, default=None)),
            ],
            options={
                'db_table': 'AccFactor',
            },
        ),

        migrations.CreateModel(
            name='AccFactorHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=None)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=False)),
                ('updated_on', models.DateTimeField(db_column='UpdatedOn', default=None)),
                ('updated_by', models.TextField(db_column='UpdatedBy', default=None)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None)),
                ('comments', models.TextField(db_column='Comments', default=None)),
                ('acc_factor_version_id', models.BigAutoField(db_column='AccFactorVersionID', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('acc_factor', models.TextField(db_column='AccFactor', max_length=40, null=True, default=None)),
                ('tm_acc_factor_code', models.TextField(db_column='TMAccFactorCode', max_length=10, null=True, default=None)),
                ('acc_factor_id', models.ForeignKey(db_column='AccFactorID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccFactor', related_name='+')),
            ],
            options={
                'db_table': 'AccFactor_History',
            },
        ),

        migrations.CreateModel(
            name='AccRangeType',
            fields=[
                ('acc_range_type_id', models.BigAutoField(db_column='AccRangeTypeID', primary_key=True, serialize=False)),
                ('tm_range_type_code', models.TextField(db_column='TMRangeTypeCode', max_length=10, null=True, default=None)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('tm_range_type', models.TextField(db_column='TMRangeType', max_length=40, null=True, default=None)),
            ],
            options={
                'db_table': 'AccRangeType',
            },
        ),

        migrations.CreateModel(
            name='AccRangeTypeHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=None)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=False)),
                ('updated_on', models.DateTimeField(db_column='UpdatedOn', default=None)),
                ('updated_by', models.TextField(db_column='UpdatedBy', default=None)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None)),
                ('comments', models.TextField(db_column='Comments', default=None)),
                ('acc_range_type_id', models.ForeignKey(db_column='AccRangeTypeID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccRangeType', related_name='+')),
                ('acc_range_type_version_id', models.BigAutoField(db_column='AccRangeTypeVersionID', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('tm_range_type', models.TextField(db_column='TMRangeType', max_length=40, null=True, default=None)),
                ('tm_range_type_code', models.BigIntegerField(db_column='TMRangeTypeCode', default=None)),
            ],
            options={
                'db_table': 'AccRangeType_History',
            },
        ),

        migrations.CreateModel(
            name='AccessorialDetail',
            fields=[
                ('acc_detail_id', models.BigAutoField(db_column='AccDetailID', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('tmacc_detail_id', models.BigIntegerField(db_column='TMAccDetailID', default=None)),
                ('allow_between', models.BooleanField(db_column='AllowBetween', default=False)),
                ('carrier_movement_type', models.TextField(db_column='CarrierMovementType', max_length=1, null=True, default=None)),
                ('acc_rate_custom_maximum', models.DecimalField(db_column='AccRateCustomMaximum', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_custom_minimum', models.DecimalField(db_column='AccRateCustomMinimum', decimal_places=6, max_digits=19, null=True, default=None)),
                ('description', models.TextField(db_column='Description', max_length=40, null=True, default=None)),
                ('effective_from', models.DateTimeField(db_column='EffectiveFrom', null=True, default=None)),
                ('effective_to', models.DateTimeField(db_column='EffectiveTo', null=True, default=None)),
                ('origin_zone_type', models.TextField(db_column='OriginZoneType', max_length=10, null=True, default=None)),
                ('origin_zone_id', models.ForeignKey(db_column='OriginZoneID', on_delete=django.db.models.deletion.CASCADE, to='rrf.Zone', related_name='+')),
                ('destination_zone_type', models.TextField(db_column='DestinationZoneType', max_length=10, null=True, default=None)),
                ('destination_zone_id', models.ForeignKey(db_column='DestinationZoneID', on_delete=django.db.models.deletion.CASCADE, to='rrf.Zone', related_name='+')),
                ('acc_rate_dock', models.BooleanField(db_column='AccRateDock', default=False)),
                ('acc_rate_DOE_factorA', models.DecimalField(db_column='AccRateDOEFactorA', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_DOE_factorB', models.DecimalField(db_column='AccRateDOEFactorB', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_elevator', models.BooleanField(db_column='AccRateElevator', default=False)),
                ('acc_rate_exclude_legs', models.BooleanField(db_column='AccRateExcludeLegs', default=False)),
                ('acc_rate_extra_stop_rates', models.TextField(db_column='AccRateExtraStopRates', max_length=4000, null=True, default=None)),
                ('acc_rate_increment', models.DecimalField(db_column='AccRateIncrement', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_fuel_price_average', models.TextField(db_column='AccRateFuelPriceAverage', max_length=10, null=True, default=None)),
                ('acc_rate_max_charge', models.DecimalField(db_column='AccRateMaxCharge', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_min_charge', models.DecimalField(db_column='AccRateMinCharge', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_percent', models.DecimalField(db_column='AccRatePercent', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_range_from1', models.DecimalField(db_column='AccRateRangeFrom1', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_range_to1', models.DecimalField(db_column='AccRateRangeTo1', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_range_from2', models.DecimalField(db_column='AccRateRangeFrom2', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_range_to2', models.DecimalField(db_column='AccRateRangeTo2', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_shipping_instructionID', models.BigIntegerField(db_column='AccRateShippingInstructionID', default=None, null=True)),
                ('acc_rate_survey', models.BooleanField(db_column='AccRateSurvey', default=False)),
                ('acc_rate_stairs', models.BooleanField(db_column='AccRateStairs', default=False)),
                ('acc_rate_status_code', models.TextField(db_column='AccRateStatusCode', max_length=10, null=True, default=None)),
                ('acc_rate_threshold_amount', models.DecimalField(db_column='AccRateThresholdAmount', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_vehicle_restricted', models.BooleanField(db_column='AccRateVehicleRestricted', default=False)),
                ('min_std_charge', models.DecimalField(db_column='MinStdCharge', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_header_id', models.ForeignKey(db_column='AccHeaderID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccessorialHeader')),
                ('acc_rate_factor_id', models.ForeignKey(db_column='AccRateFactorID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccFactor')),
                ('acc_rate_range_field1ID', models.ForeignKey(db_column='AccRangeTypeID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccRangeType')),
                ('acc_rate_range_field2ID', models.BigIntegerField(db_column='AccRateRangeField2ID', default=None)),
                ('commodity_id', models.ForeignKey(db_column='CommodityID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Commodity')),
                ('sub_service_level_id', models.ForeignKey(db_column='SubServiceLevelID', on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevel', related_name='+')),
                ('free_time_id', models.ForeignKey(db_column='FreeTimeID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.FreeTime')),
            ],
            options={
                'db_table': 'AccessorialDetail',
            },
        ),

        migrations.CreateModel(
            name='AccessorialDetailHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=None)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=False)),
                ('updated_on', models.DateTimeField(db_column='UpdatedOn', default=None)),
                ('updated_by', models.TextField(db_column='UpdatedBy', default=None)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None)),
                ('comments', models.TextField(db_column='Comments', default=None)),
                ('acc_detail_version_id', models.BigAutoField(db_column='AccDetailVersionID', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('tmacc_detail_id', models.BigIntegerField(db_column='TMAccDetailID', default=None)),
                ('acc_header_version_id', models.BigIntegerField(db_column='AccountHeader', default=None)),
                ('allow_between', models.BooleanField(db_column='AllowBetween', default=False)),
                ('carrier_movement_type', models.TextField(db_column='CarrierMovementType', max_length=1, null=True, default=None)),
                ('acc_rate_custom_maximum', models.DecimalField(db_column='AccRateCustomMaximum', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_custom_minimum', models.DecimalField(db_column='AccRateCustomMinimum', decimal_places=6, max_digits=19, null=True, default=None)),
                ('description', models.TextField(db_column='Description', max_length=40, null=True, default=None)),
                ('effective_from', models.DateTimeField(db_column='EffectiveFrom', null=True, default=None)),
                ('effective_to', models.DateTimeField(db_column='EffectiveTo', null=True, default=None)),
                ('origin_zone_type', models.TextField(db_column='OriginZoneType', max_length=10, null=True, default=None)),
                ('destination_zone_type', models.TextField(db_column='DestinationZoneType', max_length=10, null=True, default=None)),
                ('acc_rate_dock', models.BooleanField(db_column='AccRateDock', default=False)),
                ('acc_rate_DOE_factorA', models.DecimalField(db_column='AccRateDOEFactorA', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_DOE_factorB', models.DecimalField(db_column='AccRateDOEFactorB', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_elevator', models.BooleanField(db_column='AccRateElevator', default=False)),
                ('acc_rate_exclude_legs', models.BooleanField(db_column='AccRateExcludeLegs', default=False)),
                ('acc_rate_extra_stop_rates', models.TextField(db_column='AccRateExtraStopRates', max_length=4000, null=True, default=None)),
                ('acc_rate_increment', models.DecimalField(db_column='AccRateIncrement', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_fuel_price_average', models.TextField(db_column='AccRateFuelPriceAverage', max_length=10, null=True, default=None)),
                ('acc_rate_max_charge', models.DecimalField(db_column='AccRateMaxCharge', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_min_charge', models.DecimalField(db_column='AccRateMinCharge', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_percent', models.DecimalField(db_column='AccRatePercent', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_range_field_version2_id', models.BigIntegerField(db_column='AccRateRangeFieldVersion2ID', default=None, null=True)),
                ('acc_rate_range_from1', models.DecimalField(db_column='AccRateRangeFrom1', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_range_to1', models.DecimalField(db_column='AccRateRangeTo1', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_range_from2', models.DecimalField(db_column='AccRateRangeFrom2', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_range_to2', models.DecimalField(db_column='AccRateRangeTo2', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_shipping_instructionID', models.BigIntegerField(db_column='AccRateShippingInstructionID', default=None, null=True)),
                ('acc_rate_survey', models.BooleanField(db_column='AccRateSurvey', default=False)),
                ('acc_rate_stairs', models.BooleanField(db_column='AccRateStairs', default=False)),
                ('acc_rate_status_code', models.TextField(db_column='AccRateStatusCode', max_length=10, null=True, default=None)),
                ('acc_rate_threshold_amount', models.DecimalField(db_column='AccRateThresholdAmount', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_vehicle_restricted', models.BooleanField(db_column='AccRateVehicleRestricted', default=False)),
                ('min_std_charge', models.DecimalField(db_column='MinStdCharge', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_rate_factor_version_id', models.ForeignKey(db_column='AccRateFactorVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccFactorHistory')),
                ('acc_range_type_version_id', models.ForeignKey(db_column='AccRangeTypeVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccRangeTypeHistory')),
                ('commodity_version_id', models.ForeignKey(db_column='CommodityVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.CommodityHistory')),
                ('sub_service_level_version_id', models.ForeignKey(db_column='SubServiceLevelVersionID', on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevelHistory', related_name='+')),
                ('acc_detail_id', models.ForeignKey(db_column='AccDetailID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccessorialDetail', related_name='+')),
                ('destination_zone_id', models.ForeignKey(db_column='DestinationZoneID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccessorialDetail', related_name='+')),
                ('free_time_id', models.ForeignKey(db_column='FreeTimeID', on_delete=django.db.models.deletion.CASCADE, to='rrf.FreeTime', related_name='+')),
                ('origin_zone_id', models.ForeignKey(db_column='OriginZoneID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccessorialDetail', related_name='+')),
            ],
            options={
                'db_table': 'AccessorialDetail_History',
            },
        ),

        migrations.CreateModel(
            name='AccessorialDetention',
            fields=[
                ('acc_detention_id', models.BigAutoField(db_column='AccDetentionID', primary_key=True, serialize=False)),
                ('acc_header_id', models.ForeignKey(db_column='AccHeaderID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccessorialHeader')),
                ('tm_detention_id', models.BigIntegerField(db_column='TMDetentionID', default=None)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('base_rate', models.BooleanField(db_column='BaseRate', default=False)),
                ('description', models.TextField(db_column='Description', max_length=40, null=True, default=None)),
                ('detention_type', models.TextField(db_column='DetentionType', max_length=10, null=True, default=None)),
                ('effective_from', models.DateTimeField(db_column='EffectiveFrom', default=None)),
                ('effective_to', models.DateTimeField(db_column='EffectiveTo', default=None)),
                ('exclude_closed_days_detention', models.TextField(db_column='ExcludeClosedDaysDetention', max_length=20, null=True, default=None)),
                ('exclude_closed_days_freetime', models.TextField(db_column='ExcludeClosedDaysFreeTime', max_length=20, null=True, default=None)),
                ('fb_based_date_field', models.TextField(db_column='FBBasedDateField', max_length=10, null=True, default=None)),
                ('free_time_unit', models.TextField(db_column='FreeTimeUnit', max_length=3, null=True, default=None)),
                ('freetime_unit_to_measure', models.TextField(db_column='FreeTimeUnitofMeasure', max_length=10, null=True, default=None)),
                ('inter_company', models.TextField(db_column='InterCompany', max_length=5, null=True, default=None)),
                ('late_no_bill', models.TextField(db_column='LateNoBill', max_length=5, null=True, default=None)),
                ('late_window', models.DecimalField(db_column='LateWindow', decimal_places=6, max_digits=19, null=True, default=None)),
                ('ltl_proration_method', models.TextField(db_column='LtlProrationMethod', max_length=10, null=True, default=None)),
                ('max_bill_time', models.DecimalField(db_column='MaxBillTime', decimal_places=6, max_digits=19, null=True, default=None)),
                ('min_bill_time', models.DecimalField(db_column='MinBillTime', decimal_places=6, max_digits=19, null=True, default=None)),
                ('free_times', models.TextField(db_column='FreeTimes', max_length=4000, null=True, default=None)),
                ('operations_code', models.TextField(db_column='OperationsCode', max_length=10, null=True, default=None)),
                ('payment_option', models.TextField(db_column='PaymentOption', max_length=10, null=True, default=None)),
                ('second_bill_rate', models.DecimalField(db_column='SecondBillRate', decimal_places=6, max_digits=19, null=True, default=None)),
                ('shipper', models.TextField(db_column='Shipper', max_length=10, null=True, default=None)),
                ('shipper_group', models.TextField(db_column='ShipperGroup', max_length=10, null=True, default=None)),
                ('origin_zone_type', models.TextField(db_column='OriginZoneType', max_length=10, null=True, default=None)),
                ('destination_zone_type', models.TextField(db_column='DestinationZoneType', max_length=40, null=True, default=None)),
                ('origin_zone_id', models.ForeignKey(db_column='ZoneID', on_delete=django.db.models.deletion.CASCADE, to='rrf.Zone', related_name='+')),
                ('destination_zone_id', models.BigIntegerField(db_column='DestinationZoneID', default=None)),
                ('start_bill_rate', models.DecimalField(db_column='StartBillRate', decimal_places=6, max_digits=19, null=True, default=None)),
                ('start_option', models.TextField(db_column='StartOption', max_length=40, null=True, default=None)),
                ('stop_option', models.TextField(db_column='StopOption', max_length=40, null=True, default=None)),
                ('use_actual_time', models.BooleanField(db_column='UseActualTime', default=False)),
                ('warning_send', models.TextField(db_column='WarningSend', max_length=5, null=True, default=None)),
                ('warning_time', models.DecimalField(db_column='WarningTime', decimal_places=6, max_digits=19, null=True, default=None)),
                ('min_std_charge', models.DecimalField(db_column='MinStdCharge', decimal_places=6, max_digits=19, null=True, default=None)),
                ('currency_id', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.CASCADE, to='rrf.Currency', related_name='+')),
                ('equipment_type_id', models.ForeignKey(db_column='EquipmentTypeID', on_delete=django.db.models.deletion.CASCADE, to='rrf.EquipmentType', related_name='+')),
                ('sub_service_level_id', models.ForeignKey(db_column='SubServiceLevelID', on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevel', related_name='+')),
                ('free_time_id', models.ForeignKey(db_column='FreeTimeID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.FreeTime')),
            ],
            options={
                'db_table': 'AccessorialDetention',
            },
        ),

        migrations.CreateModel(
            name='AccessorialDetentionHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=None)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=False)),
                ('updated_on', models.DateTimeField(db_column='UpdatedOn', default=None)),
                ('updated_by', models.TextField(db_column='UpdatedBy', default=None)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None)),
                ('comments', models.TextField(db_column='Comments', default=None)),
                ('acc_detention_version_id', models.BigAutoField(db_column='AccDetentionVersionID', primary_key=True, serialize=False)),
                ('tm_detention_id', models.BigIntegerField(db_column='TMDetentionID', default=None)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('base_rate', models.BooleanField(db_column='BaseRate', default=False)),
                ('description', models.TextField(db_column='Description', max_length=40, null=True, default=None)),
                ('detention_type', models.TextField(db_column='DetentionType', max_length=10, null=True, default=None)),
                ('effective_from', models.DateTimeField(db_column='EffectiveFrom', default=None)),
                ('effective_to', models.DateTimeField(db_column='EffectiveTo', default=None)),
                ('exclude_closed_days_detention', models.TextField(db_column='ExcludeClosedDaysDetention', max_length=20, null=True, default=None)),
                ('exclude_closed_days_freetime', models.TextField(db_column='ExcludeClosedDaysFreeTime', max_length=20, null=True, default=None)),
                ('fb_based_date_field', models.TextField(db_column='FBBasedDateField', max_length=10, null=True, default=None)),
		        ('free_time_version_id', models.ForeignKey(db_column='FreeTimeVersionID', on_delete=django.db.models.deletion.CASCADE, to='rrf.FreeTimeHistory', related_name='+')),
                ('free_time_unit', models.TextField(db_column='FreeTimeUnit', max_length=3, null=True, default=None)),
                ('freetime_unit_to_measure', models.TextField(db_column='FreeTimeUnitofMeasure', max_length=10, null=True, default=None)),
                ('inter_company', models.TextField(db_column='InterCompany', max_length=5, null=True, default=None)),
                ('late_no_bill', models.TextField(db_column='LateNoBill', max_length=5, null=True, default=None)),
                ('late_window', models.DecimalField(db_column='LateWindow', decimal_places=6, max_digits=19, null=True, default=None)),
                ('ltl_proration_method', models.TextField(db_column='LtlProrationMethod', max_length=10, null=True, default=None)),
                ('max_bill_time', models.DecimalField(db_column='MaxBillTime', decimal_places=6, max_digits=19, null=True, default=None)),
                ('min_bill_time', models.DecimalField(db_column='MinBillTime', decimal_places=6, max_digits=19, null=True, default=None)),
                ('free_times', models.TextField(db_column='FreeTimes', max_length=4000, null=True, default=None)),
                ('operations_code', models.TextField(db_column='OperationsCode', max_length=10, null=True, default=None)),
                ('payment_option', models.TextField(db_column='PaymentOption', max_length=10, null=True, default=None)),
                ('second_bill_rate', models.DecimalField(db_column='SecondBillRate', decimal_places=6, max_digits=19, null=True, default=None)),
                ('shipper', models.TextField(db_column='Shipper', max_length=10, null=True, default=None)),
                ('shipper_group', models.TextField(db_column='ShipperGroup', max_length=10, null=True, default=None)),
                ('origin_zone_type', models.TextField(db_column='OriginZoneType', max_length=10, null=True, default=None)),
                ('origin_zone_version_id', models.ForeignKey(db_column='OriginZoneVersionID', on_delete=django.db.models.deletion.CASCADE, to='rrf.ZoneHistory', related_name='+')),
                ('destination_zone_type', models.TextField(db_column='DestinationZoneType', max_length=40, null=True, default=None)),
                ('destination_zone_version_id', models.ForeignKey(db_column='DestinationZoneVersionID', on_delete=django.db.models.deletion.CASCADE, to='rrf.ZoneHistory', related_name='+')),
                ('start_bill_rate', models.DecimalField(db_column='StartBillRate', decimal_places=6, max_digits=19, null=True, default=None)),
                ('start_option', models.TextField(db_column='StartOption', max_length=40, null=True, default=None)),
                ('stop_option', models.TextField(db_column='StopOption', max_length=40, null=True, default=None)),
                ('use_actual_time', models.BooleanField(db_column='UseActualTime', default=False)),
                ('warning_send', models.TextField(db_column='WarningSend', max_length=5, null=True, default=None)),
                ('warning_time', models.DecimalField(db_column='WarningTime', decimal_places=6, max_digits=19, null=True, default=None)),
                ('min_std_charge', models.DecimalField(db_column='MinStdCharge', decimal_places=6, max_digits=19, null=True, default=None)),
                ('acc_header_version_id', models.ForeignKey(db_column='AccHeaderVersionID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccessorialHeaderHistory', related_name='+')),
                ('currency_version_id', models.ForeignKey(db_column='CurrencyVersionID', on_delete=django.db.models.deletion.CASCADE, to='rrf.CurrencyHistory', related_name='+')),
                ('equipment_type_version_id', models.ForeignKey(db_column='EquipmentTypeVersionID', on_delete=django.db.models.deletion.CASCADE, to='rrf.EquipmentTypeHistory', related_name='+')),
                ('sub_service_level_version_id', models.ForeignKey(db_column='SubServiceLevelVersionID', on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevelHistory')),
                ('acc_detention_id', models.ForeignKey(db_column='AccDetentionID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccessorialDetention')),
            ],
            options={
                'db_table': 'AccessorialDetention_History',
            },
        ),

        migrations.CreateModel(
            name='AccessorialHeader',
            fields=[
                ('acc_header_id', models.BigAutoField(db_column='AccHeaderID', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('tmacc_charge_code', models.TextField(db_column='TMAccChargeCode', max_length=10, null=True, default=None)),
                ('dangerous_goods', models.BooleanField(db_column='DangerousGoods', default=False)),
                ('description', models.TextField(db_column='Description', max_length=40, null=True, default=None)),
                ('temperature_controlled', models.BooleanField(db_column='TemperatureControlled', default=False)),
                ('business_grouping', models.BigIntegerField(db_column='BusinessGrouping', default=None)),
                ('acc_charge_behavior_id', models.ForeignKey(db_column='AccChargeBehaviorID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccChargeBehavior', related_name='+')),
                ('acc_range_field_id', models.ForeignKey(db_column='AccRangeFieldID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccRangeType', related_name='+')),
                ('currency_id', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.CASCADE, to='rrf.Currency', related_name='+')),
            ],
            options={
                'db_table': 'AccessorialHeader',
            },
        ),

        migrations.CreateModel(
            name='AccessorialHeaderHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=None)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=False)),
                ('updated_on', models.DateTimeField(db_column='UpdatedOn', default=None)),
                ('updated_by', models.TextField(db_column='UpdatedBy', default=None)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None)),
                ('comments', models.TextField(db_column='Comments', default=None)),
                ('acc_header_id', models.ForeignKey(db_column='AccHeaderID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccessorialHeader', related_name='+')),
                ('acc_header_version_id', models.BigAutoField(db_column='AccHeaderVersionID', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('tmacc_charge_code', models.TextField(db_column='TMAccChargeCode', max_length=10, null=True, default=None)),
                ('dangerous_goods', models.BooleanField(db_column='DangerousGoods', default=False)),
                ('description', models.TextField(db_column='Description', max_length=40, null=True, default=None)),
                ('temperature_controlled', models.BooleanField(db_column='TemperatureControlled', default=False)),
                ('business_grouping', models.BigIntegerField(db_column='BusinessGrouping', default=None)),
                ('acc_charge_behavior_version_id', models.ForeignKey(db_column='AccChargeBehaviorVersionID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccChargeBehaviorHistory', related_name='+')),
                ('acc_range_field_version_id', models.ForeignKey(db_column='AccRangeFieldVersionID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccRangeTypeHistory', related_name='+')),
                ('currency_version_id', models.ForeignKey(db_column='CurrencyVersionID', on_delete=django.db.models.deletion.CASCADE, to='rrf.CurrencyHistory', related_name='+')),
            ],
            options={
                'db_table': 'AccessorialHeader_History',
            },
        ),

        migrations.CreateModel(
            name='AccessorialStorage',
            fields=[
                ('acc_storage_id', models.BigAutoField(db_column='AccStorageID', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('tm_storage_id', models.BigIntegerField(db_column='TMStorageID', default=None)),
                ('base_rate', models.BooleanField(db_column='BaseRate', default=False)),
                ('bill_option', models.TextField(db_column='BillOption', max_length=1, null=True, default=None)),
                ('dangerous_goods', models.BooleanField(db_column='DangerousGoods', default=False)),
                ('description', models.TextField(db_column='Description', max_length=40, null=True, default=None)),
                ('effective_from', models.DateTimeField(db_column='EffectiveFrom', default=None)),
                ('effective_to', models.DateTimeField(db_column='EffectiveTo', default=None)),
                ('free_days', models.BigIntegerField(db_column='FreeDays', default=None)),
                ('high_value', models.BooleanField(db_column='HighValue', default=False)),
                ('include_delivery_day', models.BooleanField(db_column='IncludeDeliveryDay', default=False)),
                ('include_terminal_service_calendar', models.BooleanField(db_column='IncludeTerminalServiceCalendar', default=False)),
                ('operations_code', models.TextField(db_column='OperationsCode', max_length=10, null=True, default=None)),
                ('rate_amount', models.DecimalField(db_column='RateAmount', decimal_places=6, max_digits=19, null=True, default=None)),
                ('rate_max', models.DecimalField(db_column='RateMax', decimal_places=6, max_digits=19, null=True, default=None)),
                ('rate_min', models.DecimalField(db_column='RateMin', decimal_places=6, max_digits=19, null=True, default=None)),
                ('rate_per', models.DecimalField(db_column='RatePer', decimal_places=6, max_digits=19, null=True, default=None)),
                ('temp_controlled', models.BooleanField(db_column='TempControlled', default=False)),
                ('acc_header_id', models.ForeignKey(db_column='AccHeaderID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccessorialHeader')),
                ('currency_id', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Currency')),
                ('sub_service_level_id', models.ForeignKey(db_column='SubServiceLevelID', on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevel')),
                ('unit_id', models.ForeignKey(db_column='UnitID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.Unit')),
                ('min_std_charge', models.DecimalField(db_column='MinStdCharge', decimal_places=6, max_digits=19, null=True, default=None)),
            ],
            options={
                'db_table': 'AccessorialStorage',
            },
        ),

        migrations.CreateModel(
            name='AccessorialStorageHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=None)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=False)),
                ('updated_on', models.DateTimeField(db_column='UpdatedOn', default=None)),
                ('updated_by', models.TextField(db_column='UpdatedBy', default=None)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None)),
                ('comments', models.TextField(db_column='Comments', default=None)),
                ('acc_storage_id', models.ForeignKey(db_column='AccStorageID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccessorialStorage')),
                ('acc_storage_version_id', models.BigAutoField(db_column='AccStorageVersionID', primary_key=True, serialize=False)),
                ('acc_header_version_id', models.ForeignKey(db_column='AccHeaderVersionID', on_delete=django.db.models.deletion.CASCADE, to='rrf.AccessorialHeaderHistory', related_name='+')),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('tm_storage_id', models.BigIntegerField(db_column='TMStorageID', default=None)),
                ('base_rate', models.BooleanField(db_column='BaseRate', default=False)),
                ('bill_option', models.TextField(db_column='BillOption', max_length=1, null=True, default=None)),
                ('dangerous_goods', models.BooleanField(db_column='DangerousGoods', default=False)),
                ('description', models.TextField(db_column='Description', max_length=40, null=True, default=None)),
                ('effective_from', models.DateTimeField(db_column='EffectiveFrom', default=None)),
                ('effective_to', models.DateTimeField(db_column='EffectiveTo', default=None)),
                ('free_days', models.BigIntegerField(db_column='FreeDays', default=None)),
                ('high_value', models.BooleanField(db_column='HighValue', default=False)),
                ('include_delivery_day', models.BooleanField(db_column='IncludeDeliveryDay', default=False)),
                ('include_terminal_service_calendar', models.BooleanField(db_column='IncludeTerminalServiceCalendar', default=False)),
                ('operations_code', models.TextField(db_column='OperationsCode', max_length=10, null=True, default=None)),
                ('rate_amount', models.DecimalField(db_column='RateAmount', decimal_places=6, max_digits=19, null=True, default=None)),
                ('rate_max', models.DecimalField(db_column='RateMax', decimal_places=6, max_digits=19, null=True, default=None)),
                ('rate_min', models.DecimalField(db_column='RateMin', decimal_places=6, max_digits=19, null=True, default=None)),
                ('rate_per', models.DecimalField(db_column='RatePer', decimal_places=6, max_digits=19, null=True, default=None)),
                ('temp_controlled', models.BooleanField(db_column='TempControlled', default=False)),
                ('currency_version_id', models.ForeignKey(db_column='CurrencyVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.CurrencyHistory')),
                ('sub_service_level_version_id', models.ForeignKey(db_column='SubServiceLevelVersionID', on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevelHistory')),
                ('unit_version_id', models.ForeignKey(db_column='UnitVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.UnitHistory')),
                ('min_std_charge', models.DecimalField(db_column='MinStdCharge', decimal_places=6, max_digits=19, null=True, default=None)),
            ],
            options={
                'db_table': 'AccessorialStorage_History',
            },
        ),

        migrations.AlterIndexTogether(
            name='accrangetypehistory',
            index_together={('acc_range_type_version_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='accfactorhistory',
            index_together={('acc_factor_version_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='accessorialstoragehistory',
            index_together={('acc_storage_version_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='accessorialheaderhistory',
            index_together={('acc_header_version_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='accessorialdetentionhistory',
            index_together={('acc_detention_version_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='accessorialdetailhistory',
            index_together={('acc_detail_version_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='accchargebehaviorhistory',
            index_together={('acc_charge_behavior_version_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='freetimehistory',
            index_together={('free_time_version_id', 'version_num')},
        ),

    ]
