# Generated by Django 2.1.13 on 2022-04-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0044_auto_20220412_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='flagged_count',
            field=models.IntegerField(db_column='FlaggedCount', default=0),
        ),
        migrations.AddField(
            model_name='importfile',
            name='unserviceable_count',
            field=models.IntegerField(db_column='UnserviceableCount', default=0),
        ),
    ]
