# Generated by Django 2.1.13 on 2022-04-13 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0045_auto_20220413_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_owner',
        ),
    ]
