# Generated by Django 2.1.13 on 2022-04-13 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrf', '0046_remove_request_request_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_owner',
            field=models.ForeignKey(db_column='RequestOwner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
