# Generated by Django 2.1.13 on 2022-04-19 15:52

from django.db import migrations, connection


class Migration(migrations.Migration):
    #Insert Account_number as 0 for Non-Customer Tariff Requests
    def insert_non_customer_tariff_account(apps, schema_editor):
        cursor_update = connection.cursor()
        sql_insert = """
        INSERT INTO [dbo].[Account] ([IsActive],[IsInactiveViewable],[AccountNumber],[AccountName],[AccountAlias],[AddressLine1],[AddressLine2]
        ,[PostalCode],[ContactName],[ContactTitle],[Phone],[Email],[Website],[AccountOwnerID],[CityID],[ExternalCityName],[ExternalERPID])
         VALUES
            (0, 0, 0, 'Non Customer Tariff', NULL, 'Non Customer Tariff Account', NULL, '000000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
            """
        cursor_update.execute(sql_insert)

    dependencies = [
        ('rrf', '0047_request_request_owner'),
    ]

    operations = [
        migrations.RunPython(insert_non_customer_tariff_account),
    ]
