# Generated by Django 2.1.13 on 2022-04-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0045_auto_20220413_0913'),
        ('rrf', '0048_auto_20220419_1252'),
    ]

    operations = [
    ]
