# Generated by Django 2.1.13 on 2022-04-21 12:36

from django.db import migrations, models, connection

def drop_acc_tables_if_exists(apps, schema_editor):
    try:
        cursor_drop_acc_tables = connection.cursor()
        sql_drop_acc_tables = """
                    DROP TABLE IF EXISTS
                    dbo.CustomerZones_History, dbo.SubPostalCode_History
                    ;"""
        cursor_drop_acc_tables.execute(sql_drop_acc_tables)

    except Exception as e:
        raise e

class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0050_auto_20220421_0825'),
    ]

    operations = [

        # Invoke drop_acc_tables_if_exists
        migrations.RunPython(drop_acc_tables_if_exists, reverse_code=migrations.RunPython.noop),

        migrations.CreateModel(
            name='SubPostalCodeHistory',
            fields=[

            ('version_num',models.IntegerField(
                default=False, null=False, db_column="VersionNum")),
            ('is_latest_version',models.BooleanField(
                default=False, null=False, db_column="IsLatestVersion")),
            ('updated_on',models.DateTimeField(
                default=False, null=False, db_column="UpdatedOn")),
            ('updated_by',models.TextField(
                default=False, null=False, db_column="UpdatedBy")),
            ('base_version',models.IntegerField(
                default=False, null=False, db_column="BaseVersion")),
            ('comments',models.TextField(
                default=False, null=False, db_column="Comments")),
            ('sub_postal_code_version_id',models.BigAutoField(
                max_length=8, primary_key=True, null=False, db_column="SubPostalCodeVersionID")),
            ('sub_postal_code_id',models.ForeignKey(
                to='rrf.SubPostalCode', on_delete=models.CASCADE, db_column="SubPostalCodeID")),
            ('sub_postal_code_name',models.TextField(
                max_length=40, null=True, blank=False, db_column="SubPostalCodeName")),
            ('is_active',models.BooleanField(
                default=False, null=False, db_column="IsActive")),
            ('is_inactive_viewable',models.BooleanField(
                default=False, null=False, db_column="IsInactiveViewable")),
            ('postal_code_version_id', models.ForeignKey(
                to='pac.PostalCodeHistory', on_delete=models.CASCADE, db_column="PostalCodeVersionID", related_name="+")),

            ],
            options={
                'db_table': 'SubPostalCode_History',
            },
        ),

        migrations.CreateModel(
            name='CustomerZonesHistory',
            fields=[

            ('version_num', models.IntegerField(
                default=False, null=False, db_column="VersionNum")),
            ('is_latest_version', models.BooleanField(
                default=False, null=False, db_column="IsLatestVersion")),
            ('updated_on',models.DateTimeField(
                default=False, null=False, db_column="UpdatedOn")),
            ('updated_by',models.TextField(
                default=False, null=False, db_column="UpdatedBy")),
            ('base_version',models.IntegerField(
                default=False, null=False, db_column="BaseVersion")),
            ('comments',models.TextField(
                default=False, null=False, db_column="Comments")),
            ('customer_zone_version_id',models.BigAutoField(
                primary_key=True, null=False, db_column="CustomerZoneVersionID")),
            ('customer_zone_id',models.ForeignKey(
                to='rrf.CustomerZones', on_delete=models.CASCADE, db_column="CustomerZoneID", related_name="+")),
            ('customer_zone_name', models.TextField(
                max_length=40, null=True, blank=False, db_column="CustomerZoneName")),
            ('is_active', models.BooleanField(
                default=False, null=False, db_column="IsActive")),
            ('is_inactive_viewable', models.BooleanField(
                default=False, null=False, db_column="IsInactiveViewable")),
            ('service_point_version_id', models.ForeignKey(
                to='pac.ServicePointHistory', on_delete=models.CASCADE, db_column="ServicePointVersionID", related_name="+")),
            ],
            options={
                'db_table': 'CustomerZones_History',
            },
        ),

        migrations.AlterIndexTogether(
            name='customerzoneshistory',
            index_together={('customer_zone_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='subpostalcodehistory',
            index_together={('sub_postal_code_id', 'version_num')},
        ),
    ]
