# Generated by Django 2.1.13 on 2022-04-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0050_auto_20220421_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='destination_zone_version_id',
            field=models.ForeignKey(db_column='DestinationZoneVersionID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.ZoneHistory'),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='free_time_version_id',
            field=models.ForeignKey(db_column='FreeTimeVersionID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.FreeTimeHistory'),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='origin_zone_version_id',
            field=models.ForeignKey(db_column='OriginZoneVersionID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.ZoneHistory'),
        ),
        migrations.AlterField(
            model_name='accessorialdetention',
            name='destination_zone_id',
            field=models.ForeignKey(db_column='DestinationZoneID', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Zone'),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionhistory',
            name='destination_zone_version_id',
            field=models.ForeignKey(db_column='DestinationZoneVersionID', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.ZoneHistory'),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionhistory',
            name='free_time_version_id',
            field=models.ForeignKey(db_column='FreeTimeVersionID', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.FreeTimeHistory'),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionhistory',
            name='origin_zone_version_id',
            field=models.ForeignKey(db_column='OriginZoneVersionID', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.ZoneHistory'),
        ),
        migrations.AlterIndexTogether(
            name='accchargebehaviorhistory',
            index_together={('acc_charge_behavior_id', 'version_num')},
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='destination_zone_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='free_time_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='origin_zone_id',
        ),
        migrations.AlterIndexTogether(
            name='accessorialdetailhistory',
            index_together={('acc_detail_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='accessorialdetentionhistory',
            index_together={('acc_detention_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='accessorialheaderhistory',
            index_together={('acc_header_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='accessorialstoragehistory',
            index_together={('acc_storage_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='accfactorhistory',
            index_together={('acc_factor_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='accrangetypehistory',
            index_together={('acc_range_type_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='customerzoneshistory',
            index_together={('customer_zone_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='freetimehistory',
            index_together={('free_time_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='subpostalcodehistory',
            index_together={('sub_postal_code_id', 'version_num')},
        ),
    ]
