# Generated by Django 2.1.13 on 2022-04-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0052_auto_20220421_1141'),
        ('rrf', '0051_auto_20220421_0836'),
        ('rrf', '0049_merge_20220420_1312'),
    ]

    operations = [
    ]
