# Generated by Django 2.1.13 on 2022-04-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0051_auto_20220421_0836'),
        ('rrf', '0052_auto_20220421_1141'),
    ]

    operations = [
    ]
