# Generated by Django 2.1.13 on 2022-04-21 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0013_auto_20220412_1423'),
        ('rrf', '0053_merge_20220421_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicematrixhistory',
            name='sub_service_level_id',
        ),
        migrations.AddField(
            model_name='servicematrixhistory',
            name='sub_service_level_version_id',
            field=models.ForeignKey(db_column='SubServiceLevelVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevelHistory'),
        )
    ]
