# Generated by Django 2.1.13 on 2022-04-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0054_auto_20220421_1405'),
        ('rrf', '0053_merge_20220421_1424'),
    ]

    operations = [
    ]
