# Generated by Django 2.1.13 on 2022-05-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0057_auto_20220504_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('acc_term_id', models.BigAutoField(db_column='AccTermID', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('custom_terms', models.TextField(db_column='CustomTerms', default=None, max_length=4000, null=True)),
                ('request_id', models.ForeignKey(db_column='RequestID', on_delete=django.db.models.deletion.CASCADE, to='rrf.Request')),
            ],
            options={
                'db_table': 'Terms',
            },
        ),
        migrations.CreateModel(
            name='TermsHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=None)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=False)),
                ('updated_on', models.DateTimeField(db_column='UpdatedOn', default=None)),
                ('updated_by', models.TextField(db_column='UpdatedBy', default=None)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None)),
                ('comments', models.TextField(db_column='Comments', default=None)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('acc_term_version_id', models.BigAutoField(db_column='AccTermVersionID', primary_key=True, serialize=False)),
                ('custom_terms', models.TextField(db_column='CustomTerms', default=None, max_length=4000, null=True)),
                ('acc_term_id', models.ForeignKey(db_column='AccTermID', on_delete=django.db.models.deletion.CASCADE, to='rrf.Terms')),
                ('request_version_id', models.ForeignKey(db_column='RequestVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.RequestHistory')),
            ],
            options={
                'db_table': 'Terms_History',
            },
        ),
        migrations.AlterIndexTogether(
            name='termshistory',
            index_together={('acc_term_id', 'version_num')},
        ),
    ]
