# Generated by Django 2.1.13 on 2022-05-10 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0058_auto_20220509_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='acc_rate_range_field_version1_id',
            field=models.BigIntegerField(db_column='AccRateRangeFieldVersion1ID', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetail',
            name='acc_rate_range_field1ID',
            field=models.ForeignKey(db_column='AccRateRangeField1ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccRangeType'),
        ),
    ]
