# Generated by Django 2.1.13 on 2022-05-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0058_auto_20220509_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointType',
            fields=[
                ('point_type_id', models.BigAutoField(db_column='PointTypeID', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('point_type_name', models.TextField(db_column='PointTypeName', default=None, max_length=4000)),
                ('point_type_order_id', models.IntegerField(db_column='PointTypeOrderID', default=None)),
            ],
            options={
                'db_table': 'PointType',
            },
        ),
        migrations.CreateModel(
            name='PointTypeHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=None)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=False)),
                ('updated_on', models.DateTimeField(db_column='UpdatedOn', default=None)),
                ('updated_by', models.TextField(db_column='UpdatedBy', default=None)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None)),
                ('comments', models.TextField(db_column='Comments', default=None)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('point_type_version_id', models.BigAutoField(db_column='PointTypeVersionID', primary_key=True, serialize=False)),
                ('point_type_name', models.TextField(db_column='PointTypeName', default=None, max_length=4000)),
                ('point_type_order_id', models.IntegerField(db_column='PointTypeOrderID', default=None)),
                ('point_type_id', models.ForeignKey(db_column='PointTypeID', on_delete=django.db.models.deletion.CASCADE, to='rrf.Terms')),
            ],
            options={
                'db_table': 'PointType_History',
            },
        ),
        migrations.AlterIndexTogether(
            name='pointtypehistory',
            index_together={('point_type_id', 'version_num')},
        ),
    ]
