# Generated by Django 2.1.13 on 2022-05-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0058_auto_20220509_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accchargebehavior',
            options={'verbose_name_plural': 'AccChargeBehavior'},
        ),
        migrations.AlterModelOptions(
            name='accchargebehaviorhistory',
            options={'verbose_name_plural': 'AccChargeBehavior_History'},
        ),
        migrations.AlterModelOptions(
            name='accessorialdetail',
            options={'verbose_name_plural': 'AccessorialDetail'},
        ),
        migrations.AlterModelOptions(
            name='accessorialdetailhistory',
            options={'verbose_name_plural': 'AccessorialDetail_History'},
        ),
        migrations.AlterModelOptions(
            name='accessorialdetention',
            options={'verbose_name_plural': 'AccessorialDetention'},
        ),
        migrations.AlterModelOptions(
            name='accessorialdetentionhistory',
            options={'verbose_name_plural': 'AccessorialDetention_History'},
        ),
        migrations.AlterModelOptions(
            name='accessorialdetentionoverride',
            options={'verbose_name_plural': 'AccessorialDetentionOverride'},
        ),
        migrations.AlterModelOptions(
            name='accessorialdetentionoverridehistory',
            options={'verbose_name_plural': 'AccessorialDetentionOverride_History'},
        ),
        migrations.AlterModelOptions(
            name='accessorialheader',
            options={'verbose_name_plural': 'AccessorialHeader'},
        ),
        migrations.AlterModelOptions(
            name='accessorialheaderhistory',
            options={'verbose_name_plural': 'AccessorialHeader_History'},
        ),
        migrations.AlterModelOptions(
            name='accessorialoverride',
            options={'verbose_name_plural': 'AccessorialOverride'},
        ),
        migrations.AlterModelOptions(
            name='accessorialoverridehistory',
            options={'verbose_name_plural': 'AccessorialOverride_History'},
        ),
        migrations.AlterModelOptions(
            name='accessorialstorage',
            options={'verbose_name_plural': 'AccessorialStorage'},
        ),
        migrations.AlterModelOptions(
            name='accessorialstoragehistory',
            options={'verbose_name_plural': 'AccessorialStorage_History'},
        ),
        migrations.AlterModelOptions(
            name='accessorialstorageoverride',
            options={'verbose_name_plural': 'AccessorialStorageOverride'},
        ),
        migrations.AlterModelOptions(
            name='accessorialstorageoverridehistory',
            options={'verbose_name_plural': 'AccessorialStorageOverride_History'},
        ),
        migrations.AlterModelOptions(
            name='accfactor',
            options={'verbose_name_plural': 'AccFactor'},
        ),
        migrations.AlterModelOptions(
            name='accfactorhistory',
            options={'verbose_name_plural': 'AccFactor_History'},
        ),
        migrations.AlterModelOptions(
            name='accounttree',
            options={'verbose_name_plural': 'AccountTree'},
        ),
        migrations.AlterModelOptions(
            name='accounttreehistory',
            options={'verbose_name_plural': 'AccountTree_History'},
        ),
        migrations.AlterModelOptions(
            name='accrangetype',
            options={'verbose_name_plural': 'AccRangeType'},
        ),
        migrations.AlterModelOptions(
            name='accrangetypehistory',
            options={'verbose_name_plural': 'AccRangeType_History'},
        ),
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name_plural': 'Commodity'},
        ),
        migrations.AlterModelOptions(
            name='commodityhistory',
            options={'verbose_name_plural': 'Commodity_History'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currency'},
        ),
        migrations.AlterModelOptions(
            name='currencyhistory',
            options={'verbose_name_plural': 'Currency_History'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='customerhistory',
            options={'verbose_name_plural': 'Customer_History'},
        ),
        migrations.AlterModelOptions(
            name='customerzones',
            options={'verbose_name_plural': 'CustomerZones'},
        ),
        migrations.AlterModelOptions(
            name='customerzoneshistory',
            options={'verbose_name_plural': 'CustomerZones_History'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name_plural': 'EquipmentType'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttypehistory',
            options={'verbose_name_plural': 'EquipmentType_History'},
        ),
        migrations.AlterModelOptions(
            name='freetime',
            options={'verbose_name_plural': 'FreeTime'},
        ),
        migrations.AlterModelOptions(
            name='freetimehistory',
            options={'verbose_name_plural': 'FreeTime_History'},
        ),
        migrations.AlterModelOptions(
            name='freightclass',
            options={'verbose_name_plural': 'FreightClass'},
        ),
        migrations.AlterModelOptions(
            name='freightclasshistory',
            options={'verbose_name_plural': 'FreightClass_History'},
        ),
        migrations.AlterModelOptions(
            name='importfile',
            options={'verbose_name_plural': 'ImportFile'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': 'Language'},
        ),
        migrations.AlterModelOptions(
            name='languagehistory',
            options={'verbose_name_plural': 'Language_History'},
        ),
        migrations.AlterModelOptions(
            name='lastassigneduser',
            options={'verbose_name_plural': 'LastAssignedUser'},
        ),
        migrations.AlterModelOptions(
            name='ratebase',
            options={'verbose_name_plural': 'RateBase'},
        ),
        migrations.AlterModelOptions(
            name='ratebasehistory',
            options={'verbose_name_plural': 'RateBase_History'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'Request'},
        ),
        migrations.AlterModelOptions(
            name='requestaccessorials',
            options={'verbose_name_plural': 'RequestAccessorials'},
        ),
        migrations.AlterModelOptions(
            name='requestaccessorialshistory',
            options={'verbose_name_plural': 'RequestAccessorials_History'},
        ),
        migrations.AlterModelOptions(
            name='requesteditorright',
            options={'verbose_name_plural': 'RequestEditorRight'},
        ),
        migrations.AlterModelOptions(
            name='requesteditorrighthistory',
            options={'verbose_name_plural': 'RequestEditorRight_History'},
        ),
        migrations.AlterModelOptions(
            name='requesthistory',
            options={'verbose_name_plural': 'Request_History'},
        ),
        migrations.AlterModelOptions(
            name='requestinformation',
            options={'verbose_name_plural': 'RequestInformation'},
        ),
        migrations.AlterModelOptions(
            name='requestinformationhistory',
            options={'verbose_name_plural': 'RequestInformation_History'},
        ),
        migrations.AlterModelOptions(
            name='requestlane',
            options={'verbose_name_plural': 'RequestLane'},
        ),
        migrations.AlterModelOptions(
            name='requestlanehistory',
            options={'verbose_name_plural': 'RequestLane_History'},
        ),
        migrations.AlterModelOptions(
            name='requestprofile',
            options={'verbose_name_plural': 'RequestProfile'},
        ),
        migrations.AlterModelOptions(
            name='requestprofilehistory',
            options={'verbose_name_plural': 'RequestProfile_History'},
        ),
        migrations.AlterModelOptions(
            name='requestqueue',
            options={'verbose_name_plural': 'RequestQueue'},
        ),
        migrations.AlterModelOptions(
            name='requestqueuehistory',
            options={'verbose_name_plural': 'RequestQueue_History'},
        ),
        migrations.AlterModelOptions(
            name='requestsection',
            options={'verbose_name_plural': 'RequestSection'},
        ),
        migrations.AlterModelOptions(
            name='requestsectionhistory',
            options={'verbose_name_plural': 'RequestSection_History'},
        ),
        migrations.AlterModelOptions(
            name='requestsectionlane',
            options={'verbose_name_plural': 'RequestSectionLane'},
        ),
        migrations.AlterModelOptions(
            name='requestsectionlanehistory',
            options={'verbose_name_plural': 'RequestSectionLane_History'},
        ),
        migrations.AlterModelOptions(
            name='requestsectionlaneimportqueue',
            options={'verbose_name_plural': 'RequestSectionLaneImportQueue'},
        ),
        migrations.AlterModelOptions(
            name='requestsectionlanepointtype',
            options={'verbose_name_plural': 'RequestSectionLanePointType'},
        ),
        migrations.AlterModelOptions(
            name='requestsectionlanepointtypehistory',
            options={'verbose_name_plural': 'RequestSectionLanePointType_History'},
        ),
        migrations.AlterModelOptions(
            name='requestsectionlanepricingpoint',
            options={'verbose_name_plural': 'RequestSectionLanePricingPoint'},
        ),
        migrations.AlterModelOptions(
            name='requestsectionlanepricingpointhistory',
            options={'verbose_name_plural': 'RequestSectionLanePricingPoint_History'},
        ),
        migrations.AlterModelOptions(
            name='requestsectionlanepricingpointimportqueue',
            options={'verbose_name_plural': 'RequestSectionLanePricingPointImportQueue'},
        ),
        migrations.AlterModelOptions(
            name='requestsectionlanestaging',
            options={'verbose_name_plural': 'RequestSectionLane_Staging'},
        ),
        migrations.AlterModelOptions(
            name='requeststatus',
            options={'verbose_name_plural': 'RequestStatus'},
        ),
        migrations.AlterModelOptions(
            name='requeststatushistory',
            options={'verbose_name_plural': 'RequestStatus_History'},
        ),
        migrations.AlterModelOptions(
            name='requeststatustype',
            options={'verbose_name_plural': 'RequestStatusType'},
        ),
        migrations.AlterModelOptions(
            name='requeststatustypehistory',
            options={'verbose_name_plural': 'RequestStatusType_History'},
        ),
        migrations.AlterModelOptions(
            name='requesttype',
            options={'verbose_name_plural': 'RequestType'},
        ),
        migrations.AlterModelOptions(
            name='requesttypehistory',
            options={'verbose_name_plural': 'RequestType_History'},
        ),
        migrations.AlterModelOptions(
            name='servicematrix',
            options={'verbose_name_plural': 'ServiceMatrix'},
        ),
        migrations.AlterModelOptions(
            name='servicematrixhistory',
            options={'verbose_name_plural': 'ServiceMatrix_History'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name_plural': 'ServiceType'},
        ),
        migrations.AlterModelOptions(
            name='servicetypehistory',
            options={'verbose_name_plural': 'ServiceType_History'},
        ),
        migrations.AlterModelOptions(
            name='subpostalcode',
            options={'verbose_name_plural': 'SubPostalCode'},
        ),
        migrations.AlterModelOptions(
            name='subpostalcodehistory',
            options={'verbose_name_plural': 'SubPostalCode_History'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name_plural': 'Tariff'},
        ),
        migrations.AlterModelOptions(
            name='tariffhistory',
            options={'verbose_name_plural': 'Tariff_History'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name_plural': 'Terms'},
        ),
        migrations.AlterModelOptions(
            name='termshistory',
            options={'verbose_name_plural': 'Terms_History'},
        ),
        migrations.AlterModelOptions(
            name='userservicelevel',
            options={'verbose_name_plural': 'UserServiceLevel'},
        ),
        migrations.AlterModelOptions(
            name='userservicelevelhistory',
            options={'verbose_name_plural': 'UserServiceLevel_History'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name_plural': 'Zone'},
        ),
        migrations.AlterModelOptions(
            name='zonehistory',
            options={'verbose_name_plural': 'Zone_History'},
        ),
        migrations.AlterIndexTogether(
            name='requesthistory',
            index_together={('request', 'version_num')},
        ),
        migrations.AlterModelTable(
            name='servicematrixhistory',
            table='ServiceMatrix_History',
        ),
        migrations.AlterModelTable(
            name='servicetypehistory',
            table='ServiceType_History',
        ),
    ]
