# Generated by Django 2.1.13 on 2022-04-08 12:28

from django.db import migrations, connection

# Method to insert values in ServiceMatrix required for PAC 2429
def insert_point_type_data(apps, schema_editor):
    cursor_update = connection.cursor()
    sql_insert = """
        MERGE INTO dbo.PointType AS tgt
        USING (VALUES
                ( 1, 1, 'Country', 1),
                ( 1, 1, 'Region', 2),
                ( 1, 1, 'Province', 3),
                ( 1, 1, 'Basing Point', 5),
                ( 1, 1, 'Service Point', 6),
                ( 1, 1, 'Terminal', 7),
                ( 1, 1, 'Postal Code', 8),
                ( 1, 1, 'Customer Zone', 4))
               as src (IsActive, IsInactiveViewable, PointTypeName, OrderID)
        ON tgt.PointTypeName = src.PointTypeName
        WHEN MATCHED THEN
        UPDATE SET PointTypeOrderId = src.OrderID
        WHEN NOT MATCHED BY TARGET THEN
        INSERT ([IsActive],[IsInactiveViewable],[PointTypeName],[PointTypeOrderID])
        VALUES (IsActive, IsInactiveViewable, PointTypeName, OrderID) ;
        """

    cursor_update.execute(sql_insert)

class Migration(migrations.Migration):
    dependencies = [
        ('rrf', '0059_auto_20220510_1214'),
    ]

    operations = [
        migrations.RunPython(insert_point_type_data),
    ]