# Generated by Django 2.1.13 on 2022-05-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0059_auto_20220510_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorialdetailhistory',
            name='acc_rate_range_field_version1_id',
            field=models.BigIntegerField(db_column='AccRateRangeField1VersionID', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetailhistory',
            name='acc_rate_range_field_version2_id',
            field=models.BigIntegerField(db_column='AccRateRangeField2VersionID', default=None, null=True),
        ),
    ]
