# Generated by Django 2.1.13 on 2022-05-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0060_auto_20220510_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessorialdetailhistory',
            old_name='acc_rate_range_field_version1_id',
            new_name='acc_rate_range_field1_version_id',
        ),
        migrations.RenameField(
            model_name='accessorialdetailhistory',
            old_name='acc_rate_range_field_version2_id',
            new_name='acc_rate_range_field2_version_id',
        ),
    ]
