# Generated by Django 2.1.13 on 2022-05-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0060_insert_point_types'),
        ('rrf', '0061_auto_20220510_1117'),
    ]

    operations = [
    ]
