# Generated by Django 2.1.13 on 2022-05-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0062_merge_20220511_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsectionlane',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlane',
            name='destination_type_id',
            field=models.ForeignKey(db_column='DestinationTypeID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AddField(
            model_name='requestsectionlane',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlane',
            name='origin_type_id',
            field=models.ForeignKey(db_column='OriginTypeID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='destination_type_version_id',
            field=models.ForeignKey(db_column='DestinationTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointTypeHistory'),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='origin_type_version_id',
            field=models.ForeignKey(db_column='OriginTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointTypeHistory'),
        ),
        migrations.AlterField(
            model_name='pointtypehistory',
            name='point_type_id',
            field=models.ForeignKey(db_column='PointTypeID', on_delete=django.db.models.deletion.CASCADE, to='rrf.PointType'),
        ),
    ]
