# Generated by Django 2.1.13 on 2022-05-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0063_auto_20220511_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessorialdetentionoverridehistory',
            name='acc_detention_override_source_id_version_id',
        ),
        migrations.RemoveField(
            model_name='accessorialoverridehistory',
            name='acc_override_source_id_version_id',
        ),
        migrations.RemoveField(
            model_name='accessorialstorageoverridehistory',
            name='acc_storage_override_source_id_version_id',
        ),
        migrations.RemoveField(
            model_name='requestsectionlanehistory',
            name='request_section_lane_source_id_version_id',
        ),
        migrations.RemoveField(
            model_name='requestsectionlanepricingpointhistory',
            name='request_section_lane_pricing_point_source_id_version_id',
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverride',
            name='is_waive',
            field=models.BooleanField(db_column='isWaive', default=False),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverride',
            name='usage_percentage',
            field=models.DecimalField(db_column='UsagePercentage', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverridehistory',
            name='acc_detention_override_source_id',
            field=models.BigIntegerField(db_column='AccDetentionOverrideSourceID', null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverridehistory',
            name='is_waive',
            field=models.BooleanField(db_column='isWaive', default=False),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverridehistory',
            name='usage_percentage',
            field=models.DecimalField(db_column='UsagePercentage', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='is_waive',
            field=models.BooleanField(db_column='isWaive', default=False),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='usage_percentage',
            field=models.DecimalField(db_column='UsagePercentage', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='acc_override_source_id',
            field=models.BigIntegerField(db_column='AccOverrideSourceID', null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='is_waive',
            field=models.BooleanField(db_column='isWaive', default=False),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='usage_percentage',
            field=models.DecimalField(db_column='UsagePercentage', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialstorageoverride',
            name='is_waive',
            field=models.BooleanField(db_column='isWaive', default=False),
        ),
        migrations.AddField(
            model_name='accessorialstorageoverride',
            name='usage_percentage',
            field=models.DecimalField(db_column='UsagePercentage', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialstorageoverridehistory',
            name='acc_storage_override_source_id',
            field=models.BigIntegerField(db_column='AccStorageOverrideSourceID', null=True),
        ),
        migrations.AddField(
            model_name='accessorialstorageoverridehistory',
            name='is_waive',
            field=models.BooleanField(db_column='isWaive', default=False),
        ),
        migrations.AddField(
            model_name='accessorialstorageoverridehistory',
            name='usage_percentage',
            field=models.DecimalField(db_column='UsagePercentage', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='request_source_id',
            field=models.BigIntegerField(db_column='RequestSourceID', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='request_section_lane_source_id',
            field=models.BigIntegerField(db_column='RequestSectionLaneSourceID', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='request_section_lane_pricing_point_source_id',
            field=models.BigIntegerField(db_column='RequestSectionLanePricingPointSourceID', null=True),
        ),
    ]
