# Generated by Django 2.1.13 on 2022-05-12 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0064_auto_20220512_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsectionlane',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1),
        ),
        migrations.AlterField(
            model_name='requestsectionlane',
            name='destination_type_id',
            field=models.ForeignKey(db_column='DestinationTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AlterField(
            model_name='requestsectionlane',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1),
        ),
        migrations.AlterField(
            model_name='requestsectionlane',
            name='origin_type_id',
            field=models.ForeignKey(db_column='OriginTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        )
    ]
