# Generated by Django 2.1.13 on 2022-05-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0065_auto_20220512_1313'),
        ('rrf', '0059_auto_20220510_1629'),
    ]

    operations = [
    ]
