# Generated by Django 2.1.13 on 2022-05-17 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0066_merge_20220517_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorialdetentionoverride',
            name='currency_id',
            field=models.ForeignKey(db_column='CurrencyID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Currency'),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionoverride',
            name='destination_zone_id',
            field=models.ForeignKey(db_column='DestinationZoneID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Zone'),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionoverride',
            name='effective_from',
            field=models.DateTimeField(db_column='EffectiveFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionoverride',
            name='effective_to',
            field=models.DateTimeField(db_column='EffectiveTo', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionoverride',
            name='equipment_type_id',
            field=models.ForeignKey(db_column='EquipmentTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.EquipmentType'),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionoverride',
            name='origin_zone_id',
            field=models.ForeignKey(db_column='ZoneID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Zone'),
        ),
        migrations.AlterField(
            model_name='accessorialheader',
            name='business_grouping',
            field=models.TextField(db_column='BusinessGrouping', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='acc_rate_dock',
            field=models.BooleanField(db_column='AccRateDock', default=1),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='acc_rate_factor_id',
            field=models.ForeignKey(db_column='AccRateFactorID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccFactor'),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='acc_rate_range_field2ID',
            field=models.BigIntegerField(db_column='AccRateRangeField2ID', default=1),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='commodity_id',
            field=models.ForeignKey(db_column='CommodityID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Commodity'),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='destination_zone_id',
            field=models.ForeignKey(db_column='DestinationZoneID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Zone'),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='effective_from',
            field=models.DateTimeField(db_column='EffectiveFrom', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='effective_to',
            field=models.DateTimeField(db_column='EffectiveTo', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='origin_zone_id',
            field=models.ForeignKey(db_column='OriginZoneID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Zone'),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='tmacc_override_id',
            field=models.BigIntegerField(db_column='TMAccOverrideID', default=1),
        ),
        migrations.AlterField(
            model_name='accessorialstorageoverride',
            name='currency_id',
            field=models.ForeignKey(db_column='CurrencyID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Currency'),
        ),
        migrations.AlterField(
            model_name='accessorialstorageoverride',
            name='effective_from',
            field=models.DateTimeField(db_column='EffectiveFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='accessorialstorageoverride',
            name='effective_to',
            field=models.DateTimeField(db_column='EffectiveTo', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='accessorialstorageoverride',
            name='tm_storage_override_id',
            field=models.BigIntegerField(db_column='TMStorageOverrideID', default=1),
        ),
        migrations.AlterField(
            model_name='accessorialstorageoverride',
            name='unit_id',
            field=models.ForeignKey(db_column='UnitID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.Unit'),
        ),
    ]
