# Generated by Django 2.1.13 on 2022-05-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0066_merge_20220516_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorialheader',
            name='business_grouping',
            field=models.TextField(db_column='BusinessGrouping', default=None, null=True),
        ),
    ]
