# Generated by Django 2.1.13 on 2022-05-16 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0066_merge_20220516_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointtype',
            options={'verbose_name_plural': 'PointType'},
        ),
        migrations.AlterModelOptions(
            name='pointtypehistory',
            options={'verbose_name_plural': 'PointType_History'},
        ),
        migrations.AddField(
            model_name='requestsectionhistory',
            name='request_section_source_version_id',
            field=models.ForeignKey(db_column='RequestSectionSourceVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.RequestSection'),
        ),
        migrations.AddField(
            model_name='servicematrix',
            name='customer_zone_id',
            field=models.ForeignKey(db_column='CustomerZoneID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.CustomerZones'),
        ),
        migrations.AddField(
            model_name='servicematrixhistory',
            name='customer_zones_version_id',
            field=models.ForeignKey(db_column='CustomerZoneVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.CustomerZonesHistory'),
        ),
        migrations.AlterField(
            model_name='requestsection',
            name='request_section_source_id',
            field=models.IntegerField(db_column='RequestSectionSourceID', null=True),
        ),
    ]
