# Generated by Django 2.1.13 on 2022-05-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0067_auto_20220516_1128'),
        ('rrf', '0064_auto_20220513_1347'),
    ]

    operations = [
    ]
