# Generated by Django 2.1.13 on 2022-05-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0068_merge_20220517_1539'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='requestsectionhistory',
            name='IX1',
        ),
        migrations.RemoveIndex(
            model_name='requestsectionhistory',
            name='IX2',
        ),
        migrations.RemoveIndex(
            model_name='requestsectionhistory',
            name='IX3',
        ),
#         migrations.RemoveField(
#             model_name='requestsection',
#             name='section_number',
#         ),
#         migrations.RemoveField(
#             model_name='requestsectionhistory',
#             name='section_number',
#         ),
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='is_flagged',
            field=models.BooleanField(db_column='IsFlagged', default=False, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='is_flagged',
            field=models.BooleanField(db_column='IsFlagged', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialheader',
            name='business_grouping',
            field=models.TextField(db_column='BusinessGrouping', default=None, null=True),
        ),
    ]
