# Generated by Django 2.1.13 on 2022-05-19 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0067_auto_20220517_1208'),
        ('rrf', '0069_auto_20220517_1539'),
        ('rrf', '0067_auto_20220516_1326'),
    ]

    operations = [
    ]
