# Generated by Django 2.1.13 on 2022-06-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0070_merge_20220518_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='acc_rate_range_field2ID',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='acc_rate_range_from1',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='acc_rate_range_from2',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='acc_rate_range_to1',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='acc_rate_range_to2',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='acc_rate_range_from1',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='acc_rate_range_from2',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='acc_rate_range_to1',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='acc_rate_range_to2',
        ),
        migrations.RemoveField(
            model_name='accessorialoverride',
            name='acc_rate_range_field2ID',
        ),
        migrations.RemoveField(
            model_name='accessorialoverride',
            name='acc_rate_range_from1',
        ),
        migrations.RemoveField(
            model_name='accessorialoverride',
            name='acc_rate_range_from2',
        ),
        migrations.RemoveField(
            model_name='accessorialoverride',
            name='acc_rate_range_to1',
        ),
        migrations.RemoveField(
            model_name='accessorialoverride',
            name='acc_rate_range_to2',
        ),
        migrations.RemoveField(
            model_name='accessorialoverridehistory',
            name='acc_rate_range_from1',
        ),
        migrations.RemoveField(
            model_name='accessorialoverridehistory',
            name='acc_rate_range_from2',
        ),
        migrations.RemoveField(
            model_name='accessorialoverridehistory',
            name='acc_rate_range_to1',
        ),
        migrations.RemoveField(
            model_name='accessorialoverridehistory',
            name='acc_rate_range_to2',
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='acc_rate_range_type_id',
            field=models.BigIntegerField(db_column='AccRateRangeTypeID', default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='max_shipment_value',
            field=models.DecimalField(db_column='MaxShipmentValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='max_weight_value',
            field=models.DecimalField(db_column='MaxWeightValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='min_shipment_value',
            field=models.DecimalField(db_column='MinShipmentValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='min_weight_value',
            field=models.DecimalField(db_column='MinWeightValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='max_shipment_value',
            field=models.DecimalField(db_column='MaxShipmentValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='max_weight_value',
            field=models.DecimalField(db_column='MaxWeightValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='min_shipment_value',
            field=models.DecimalField(db_column='MinShipmentValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='min_weight_value',
            field=models.DecimalField(db_column='MinWeightValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='acc_rate_range_type_id',
            field=models.BigIntegerField(db_column='AccRateRangeTypeID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='max_shipment_value',
            field=models.DecimalField(db_column='MaxShipmentValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='max_weight_value',
            field=models.DecimalField(db_column='MaxWeightValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='min_shipment_value',
            field=models.DecimalField(db_column='MinShipmentValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='min_weight_value',
            field=models.DecimalField(db_column='MinWeightValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='max_shipment_value',
            field=models.DecimalField(db_column='MaxShipmentValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='max_weight_value',
            field=models.DecimalField(db_column='MaxWeightValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='min_shipment_value',
            field=models.DecimalField(db_column='MinShipmentValue', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='min_weight_value',
            field=models.DecimalField(db_column='MinWeightValue', decimal_places=6, default=None, max_digits=19, null=True),
        )
    ]
