# Generated by Django 2.1.13 on 2022-06-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0071_auto_20220602_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsection',
            name='commodity',
        ),
        migrations.AddField(
            model_name='requestsection',
            name='as_rating',
            field=models.BooleanField(db_column='AsRating', default=True),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='base_rate',
            field=models.BooleanField(db_column='BaseRate', default=True),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='commodity_id',
            field=models.ForeignKey(db_column='CommodityID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.Commodity'),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='has_max',
            field=models.BooleanField(db_column='HasMax', default=True),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='has_min',
            field=models.BooleanField(db_column='HasMin', default=True),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='request_section_source_id',
            field=models.IntegerField(db_column='RequestSectionSourceID', null=True),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='unit_factor',
            field=models.DecimalField(db_column='UnitFactor', decimal_places=6, default=100, max_digits=19),
        ),
    ]
