# Generated by Django 2.1.13 on 2022-06-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0072_auto_20220602_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsectionlane',
            name='deficit',
            field=models.TextField(db_column='Deficit', default=None, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlane',
            name='embedded_cost',
            field=models.TextField(db_column='EmbeddedCost', default=None, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlane',
            name='impact_percentage',
            field=models.TextField(db_column='ImpactPercentage', default=None, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='deficit',
            field=models.TextField(db_column='Deficit', default=None, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='embedded_cost',
            field=models.TextField(db_column='EmbeddedCost', default=None, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='impact_percentage',
            field=models.TextField(db_column='ImpactPercentage', default=None, max_length=4000, null=True),
        ),
    ]
