# Generated by Django 2.1.13 on 2022-06-09 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0073_auto_20220608_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsection',
            name='num_do_not_meet_commitment_lanes',
        ),
        migrations.RemoveField(
            model_name='requestsection',
            name='num_duplicate_lanes',
        ),
        migrations.RemoveField(
            model_name='requestsection',
            name='num_edited_lanes',
        ),
        migrations.RemoveField(
            model_name='requestsection',
            name='num_lanes',
        ),
        migrations.RemoveField(
            model_name='requestsection',
            name='num_unpublished_lanes',
        ),
        migrations.AddField(
            model_name='requestsection',
            name='maximum_value',
            field=models.DecimalField(db_column='MaximumValue', decimal_places=6, default=100, max_digits=19),
        ),
        migrations.AlterField(
            model_name='requestsection',
            name='weight_break_header',
            field=models.ForeignKey(db_column='WeightBreakHeaderID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.WeightBreakHeader'),
        ),
        migrations.RemoveField(
            model_name='requestsectionhistory',
            name='num_do_not_meet_commitment_lanes',
        ),
        migrations.RemoveField(
            model_name='requestsectionhistory',
            name='num_duplicate_lanes',
        ),
        migrations.RemoveField(
            model_name='requestsectionhistory',
            name='num_edited_lanes',
        ),
        migrations.RemoveField(
            model_name='requestsectionhistory',
            name='num_lanes',
        ),
        migrations.RemoveField(
            model_name='requestsectionhistory',
            name='num_unpublished_lanes',
        ),
        migrations.AddField(
            model_name='requestsectionhistory',
            name='as_rating',
            field=models.BooleanField(db_column='AsRating', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionhistory',
            name='base_rate',
            field=models.BooleanField(db_column='BaseRate', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionhistory',
            name='has_max',
            field=models.BooleanField(db_column='HasMax', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionhistory',
            name='has_min',
            field=models.BooleanField(db_column='HasMin', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionhistory',
            name='maximum_value',
            field=models.DecimalField(db_column='MaximumValue', decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionhistory',
            name='unit_factor',
            field=models.DecimalField(db_column='UnitFactor', decimal_places=6, max_digits=19, null=True),
        ),
    ]
