# Generated by Django 2.1.13 on 2022-06-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0074_auto_20220608_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorialdetail',
            name='destination_type_id',
            field=models.ForeignKey(db_column='DestinationTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='origin_type_id',
            field=models.ForeignKey(db_column='OriginTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='destination_type_version_id',
            field=models.ForeignKey(db_column='DestinationTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointTypeHistory'),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='origin_type_version_id',
            field=models.ForeignKey(db_column='OriginTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointTypeHistory'),
        ),
        migrations.AddField(
            model_name='accessorialdetention',
            name='destination_type_id',
            field=models.ForeignKey(db_column='DestinationTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AddField(
            model_name='accessorialdetention',
            name='origin_type_id',
            field=models.ForeignKey(db_column='OriginTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AddField(
            model_name='accessorialdetentionhistory',
            name='destination_type_version_id',
            field=models.ForeignKey(db_column='DestinationTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointTypeHistory'),
        ),
        migrations.AddField(
            model_name='accessorialdetentionhistory',
            name='origin_type_version_id',
            field=models.ForeignKey(db_column='OriginTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointTypeHistory'),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverride',
            name='destination_type_id',
            field=models.ForeignKey(db_column='DestinationTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverride',
            name='origin_type_id',
            field=models.ForeignKey(db_column='OriginTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverridehistory',
            name='destination_type_version_id',
            field=models.ForeignKey(db_column='DestinationTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointTypeHistory'),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverridehistory',
            name='origin_type_version_id',
            field=models.ForeignKey(db_column='OriginTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointTypeHistory'),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='destination_type_id',
            field=models.ForeignKey(db_column='DestinationTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='origin_type_id',
            field=models.ForeignKey(db_column='OriginTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='destination_type_version_id',
            field=models.ForeignKey(db_column='DestinationTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointTypeHistory'),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='origin_type_version_id',
            field=models.ForeignKey(db_column='OriginTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointTypeHistory'),
        ),
        migrations.AlterField(
            model_name='accessorialdetention',
            name='origin_zone_id',
            field=models.ForeignKey(db_column='OriginZoneID', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='rrf.Zone'),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionoverride',
            name='origin_zone_id',
            field=models.ForeignKey(db_column='OriginZoneID', default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='rrf.Zone'),
        ),

    ]
