# Generated by Django 2.1.13 on 2022-06-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0075_auto_20220614_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorialdetentionoverride',
            name='request_section_id',
            field=models.ForeignKey(db_column='RequestSectionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.RequestSection'),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverridehistory',
            name='request_section_version_id',
            field=models.ForeignKey(db_column='RequestSectionVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.RequestSectionHistory'),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='request_section_id',
            field=models.ForeignKey(db_column='RequestSectionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.RequestSection'),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='request_section_version_id',
            field=models.ForeignKey(db_column='RequestSectionVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.RequestSectionHistory'),
        ),
        migrations.AddField(
            model_name='accessorialstorageoverride',
            name='request_section_id',
            field=models.ForeignKey(db_column='RequestSectionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.RequestSection'),
        ),
        migrations.AddField(
            model_name='accessorialstorageoverridehistory',
            name='request_section_version_id',
            field=models.ForeignKey(db_column='RequestSectionVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.RequestSectionHistory'),
        ),
    ]
