# Generated by Django 2.1.13 on 2022-06-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0076_auto_20220614_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessorialdetention',
            name='destination_zone_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetention',
            name='origin_zone_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetentionhistory',
            name='destination_zone_version_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetentionhistory',
            name='origin_zone_version_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetentionoverride',
            name='destination_zone_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetentionoverride',
            name='origin_zone_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetentionoverridehistory',
            name='destination_zone_version_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetentionoverridehistory',
            name='origin_zone_version_id',
        ),
        migrations.AddField(
            model_name='accessorialdetention',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialdetention',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialdetentionhistory',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialdetentionhistory',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverride',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverride',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverridehistory',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverridehistory',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1),
        ),
    ]
