# Generated by Django 2.1.13 on 2022-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0077_auto_20220614_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='destination_zone_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='destination_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='origin_zone_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='origin_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='destination_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='destination_zone_version_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='origin_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='origin_zone_version_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetention',
            name='destination_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetention',
            name='origin_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetentionhistory',
            name='destination_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetentionhistory',
            name='origin_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetentionoverride',
            name='destination_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetentionoverride',
            name='origin_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetentionoverridehistory',
            name='destination_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetentionoverridehistory',
            name='origin_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialoverride',
            name='destination_zone_id',
        ),
        migrations.RemoveField(
            model_name='accessorialoverride',
            name='destination_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialoverride',
            name='origin_zone_id',
        ),
        migrations.RemoveField(
            model_name='accessorialoverride',
            name='origin_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialoverridehistory',
            name='destination_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialoverridehistory',
            name='destination_zone_version_id',
        ),
        migrations.RemoveField(
            model_name='accessorialoverridehistory',
            name='origin_zone_type',
        ),
        migrations.RemoveField(
            model_name='accessorialoverridehistory',
            name='origin_zone_version_id',
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='destination_type',
            field=models.TextField(db_column='DestinationType', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='origin_type',
            field=models.TextField(db_column='OriginType', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='destination_type',
            field=models.TextField(db_column='DestinationType', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='origin_type',
            field=models.TextField(db_column='OriginType', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetention',
            name='destination_type',
            field=models.TextField(db_column='DestinationType', default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetention',
            name='origin_type',
            field=models.TextField(db_column='OriginType', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetentionhistory',
            name='destination_type',
            field=models.TextField(db_column='DestinationType', default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetentionhistory',
            name='origin_type',
            field=models.TextField(db_column='OriginType', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverride',
            name='destination_type',
            field=models.TextField(db_column='DestinationType', default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverride',
            name='origin_type',
            field=models.TextField(db_column='OriginType', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverridehistory',
            name='destination_type',
            field=models.TextField(db_column='DestinationType', default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverridehistory',
            name='origin_type',
            field=models.TextField(db_column='OriginType', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='destination_type',
            field=models.TextField(db_column='DestinationType', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='origin_type',
            field=models.TextField(db_column='OriginType', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='destination_type',
            field=models.TextField(db_column='DestinationType', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='origin_type',
            field=models.TextField(db_column='OriginType', default=None, max_length=10, null=True),
        ),
    ]
