# Generated by Django 2.1.13 on 2022-06-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0015_auto_20220615_0822'),
        ('rrf', '0078_auto_20220615_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpostalcode',
            name='terminal_id',
            field=models.ForeignKey(db_column='TerminalID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.Terminal'),
        ),
    ]
