# Generated by Django 2.1.13 on 2022-06-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0016_auto_20220615_1026'),
        ('rrf', '0079_subpostalcode_terminal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerzones',
            name='service_point_id',
        ),
        migrations.RemoveField(
            model_name='customerzoneshistory',
            name='service_point_version_id',
        ),
        migrations.RemoveField(
            model_name='subpostalcode',
            name='postal_code_id',
        ),
        migrations.RemoveField(
            model_name='subpostalcodehistory',
            name='postal_code_version_id',
        ),
        migrations.AddField(
            model_name='customerzones',
            name='customer_zone_code',
            field=models.TextField(db_column='CustomerZoneCode', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerzones',
            name='customer_zone_external_tmid',
            field=models.TextField(db_column='ExternalTMID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerzoneshistory',
            name='customer_zone_code',
            field=models.TextField(db_column='CustomerZoneCode', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerzoneshistory',
            name='customer_zone_external_tmid',
            field=models.TextField(db_column='ExternalTMID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subpostalcodehistory',
            name='terminal_version_id',
            field=models.ForeignKey(db_column='TerminalVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.TerminalHistory'),
        ),
    ]
