# Generated by Django 2.1.13 on 2022-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0080_auto_20220615_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorialdetail',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetail',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetailhistory',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetailhistory',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetention',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetention',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionhistory',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionhistory',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionoverride',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionoverride',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionoverridehistory',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionoverridehistory',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialoverridehistory',
            name='destination_id',
            field=models.BigIntegerField(db_column='DestinationID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialoverridehistory',
            name='origin_id',
            field=models.BigIntegerField(db_column='OriginID', default=1, null=True),
        ),
    ]
