# Generated by Django 2.1.13 on 2022-06-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0081_auto_20220617_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorialdetail',
            name='destination_type_id',
            field=models.ForeignKey(db_column='DestinationTypeID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AlterField(
            model_name='accessorialdetail',
            name='origin_type_id',
            field=models.ForeignKey(db_column='OriginTypeID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AlterField(
            model_name='accessorialdetention',
            name='destination_type_id',
            field=models.ForeignKey(db_column='DestinationTypeID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AlterField(
            model_name='accessorialdetention',
            name='origin_type_id',
            field=models.ForeignKey(db_column='OriginTypeID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionoverride',
            name='destination_type_id',
            field=models.ForeignKey(db_column='DestinationTypeID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionoverride',
            name='origin_type_id',
            field=models.ForeignKey(db_column='OriginTypeID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='destination_type_id',
            field=models.ForeignKey(db_column='DestinationTypeID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='origin_type_id',
            field=models.ForeignKey(db_column='OriginTypeID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.PointType'),
        ),
    ]
