# Generated by Django 2.1.13 on 2022-06-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrf', '082_add_spot_quote_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='request_owner_version_id',
            field=models.ForeignKey(blank=True, db_column='RequestOwnerVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_owner',
            field=models.ForeignKey(blank=True, db_column='RequestOwner', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='submitted_by',
            field=models.ForeignKey(blank=True, db_column='SubmittedBy', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='initiated_by_version',
            field=models.ForeignKey(blank=True, db_column='InitiatedByVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.UserHistory'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='submitted_by_version',
            field=models.ForeignKey(blank=True, db_column='SubmittedByVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.UserHistory'),
        ),
    ]
