# Generated by Django 2.1.13 on 2022-06-17 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0082_auto_20220617_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='acc_rate_range_type_version_id',
            field=models.BigIntegerField(db_column='AccRateRangeTypeVersionID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='acc_rate_range_type_id',
            field=models.BigIntegerField(db_column='AccRateRangeTypeID', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='commodity_id',
            field=models.ForeignKey(db_column='CommodityID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Commodity'),
        ),
        migrations.AlterField(
            model_name='accessorialoverride',
            name='sub_service_level_id',
            field=models.ForeignKey(db_column='SubServiceLevelID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.SubServiceLevel'),
        ),
        migrations.AlterField(
            model_name='accessorialoverridehistory',
            name='commodity_version_id',
            field=models.ForeignKey(db_column='CommodityVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.CommodityHistory'),
        ),
        migrations.AlterField(
            model_name='accessorialoverridehistory',
            name='sub_service_level_version_id',
            field=models.ForeignKey(db_column='SubServiceLevelVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.SubServiceLevelHistory'),
        ),
    ]
