# Generated by Django 2.1.13 on 2022-06-17 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0084_auto_20220617_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistory',
            name='language',
            field=models.ForeignKey(db_column='LanguageVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.Language'),
        ),
    ]
