# Generated by Django 2.1.13 on 2022-06-19 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0086_auto_20220618_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsection',
            name='commodity_id',
            field=models.ForeignKey(blank=True, db_column='CommodityID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.Commodity'),
        ),
    ]
