# Generated by Django 2.1.13 on 2022-06-19 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0087_auto_20220618_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsectionhistory',
            name='commodity_id',
            field=models.ForeignKey(db_column='CommodityVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.Commodity'),
        ),
    ]
