# Generated by Django 2.1.13 on 2022-06-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0088_auto_20220618_2146'),
        ('rrf', '0083_auto_20220617_1336'),
    ]

    operations = [
    ]
