# Generated by Django 2.1.13 on 2022-06-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0089_merge_20220620_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsectionhistory',
            name='request_section_source_version_id',
        ),
        migrations.AddField(
            model_name='requestsectionhistory',
            name='request_section_source_id',
            field=models.BigIntegerField(blank=True, db_column='RequestSectionSourceID', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='requestsection',
            name='request_section_source_id',
            field=models.BigIntegerField(blank=True, db_column='RequestSectionSourceID', default=None, null=True),
        ),
    ]
