# Generated by Django 2.1.13 on 2022-06-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0090_auto_20220620_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicematrix',
            name='basing_point_id',
        ),
        migrations.RemoveField(
            model_name='servicematrix',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='servicematrix',
            name='customer_zone_id',
        ),
        migrations.RemoveField(
            model_name='servicematrix',
            name='postal_code_id',
        ),
        migrations.RemoveField(
            model_name='servicematrix',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='servicematrix',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='servicematrix',
            name='service_point_id',
        ),
        migrations.RemoveField(
            model_name='servicematrix',
            name='terminal_id',
        ),
        migrations.RemoveField(
            model_name='servicematrix',
            name='zone_id',
        ),
        migrations.RemoveField(
            model_name='servicematrixhistory',
            name='basing_point_version_id',
        ),
        migrations.RemoveField(
            model_name='servicematrixhistory',
            name='country_version_id',
        ),
        migrations.RemoveField(
            model_name='servicematrixhistory',
            name='customer_zones_version_id',
        ),
        migrations.RemoveField(
            model_name='servicematrixhistory',
            name='postal_code_version_id',
        ),
        migrations.RemoveField(
            model_name='servicematrixhistory',
            name='province_version_id',
        ),
        migrations.RemoveField(
            model_name='servicematrixhistory',
            name='region_version_id',
        ),
        migrations.RemoveField(
            model_name='servicematrixhistory',
            name='service_point_version_id',
        ),
        migrations.RemoveField(
            model_name='servicematrixhistory',
            name='terminal_version_id',
        ),
        migrations.RemoveField(
            model_name='servicematrixhistory',
            name='zone_version_id',
        ),
        migrations.AddField(
            model_name='servicematrix',
            name='point_id',
            field=models.IntegerField(db_column='PointID', default=False),
        ),
        migrations.AddField(
            model_name='servicematrix',
            name='point_type_id',
            field=models.ForeignKey(db_column='PointTypeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.PointType'),
        ),
        migrations.AddField(
            model_name='servicematrixhistory',
            name='point_type_version_id',
            field=models.ForeignKey(db_column='PointTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.PointTypeHistory'),
        ),
        migrations.AddField(
            model_name='servicematrixhistory',
            name='point_version_id',
            field=models.IntegerField(db_column='PointVersionID', default=False),
        ),
    ]
