# Generated by Django 2.1.13 on 2022-06-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0091_auto_20220623_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicematrix',
            name='point_id',
            field=models.IntegerField(db_column='PointID', null=True),
        ),
        migrations.AlterField(
            model_name='servicematrixhistory',
            name='point_version_id',
            field=models.IntegerField(db_column='PointVersionID', null=True),
        ),
    ]
