# Generated by Django 2.1.13 on 2022-06-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0093_auto_20220630_1015'),
        ('rrf', '0094_auto_20220629_2254'),
    ]

    operations = [
    ]
