# Generated by Django 2.1.13 on 2022-07-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0095_merge_20220630_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profit_loss_summary_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='revenue_history_id',
        ),
        migrations.RemoveField(
            model_name='reviewhistory',
            name='profit_loss_summary_version_id',
        ),
        migrations.RemoveField(
            model_name='reviewhistory',
            name='revenue_history_version_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='request_id',
            field=models.ForeignKey(db_column='RequestID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Request'),
        ),
        migrations.AlterField(
            model_name='reviewhistory',
            name='request_version_id',
            field=models.ForeignKey(db_column='RequestVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.RequestHistory'),
        ),
    ]
