# Generated by Django 2.1.13 on 2022-07-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0096_auto_20220704_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestinformation',
            name='extended_payment_days',
        ),
        migrations.RemoveField(
            model_name='requestinformation',
            name='extended_payment_terms_margin',
        ),
        migrations.RemoveField(
            model_name='requestinformation',
            name='is_extended_payment',
        ),
        migrations.RemoveField(
            model_name='requestinformation',
            name='is_paying_by_credit_card',
        ),
        migrations.RemoveField(
            model_name='requestinformationhistory',
            name='extended_payment_days',
        ),
        migrations.RemoveField(
            model_name='requestinformationhistory',
            name='extended_payment_terms_margin',
        ),
        migrations.RemoveField(
            model_name='requestinformationhistory',
            name='is_extended_payment',
        ),
        migrations.RemoveField(
            model_name='requestinformationhistory',
            name='is_paying_by_credit_card',
        ),
    ]
