# Generated by Django 2.1.13 on 2022-07-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0097_auto_20220705_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitlosssummary',
            name='review_id',
            field=models.ForeignKey(db_column='ReviewID', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Review'),
        ),
        migrations.AddField(
            model_name='profitlosssummaryhistory',
            name='review_version_id',
            field=models.ForeignKey(db_column='ReviewVersionID', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.ReviewHistory'),
        ),
        migrations.AddField(
            model_name='revenuehistory',
            name='review_id',
            field=models.ForeignKey(db_column='ReviewID', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Review'),
        ),
        migrations.AddField(
            model_name='revenuehistoryhistory',
            name='review_version_id',
            field=models.ForeignKey(db_column='ReviewVersionID', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.ReviewHistory'),
        ),
    ]
