# Generated by Django 2.1.13 on 2022-07-05 21:42

from django.db import migrations, connection


# Method to insert values in LaneType
def insert_lane_type_data(apps, schema_editor):
    cursor_update = connection.cursor()
    sql_insert = """
        INSERT INTO [dbo].[LaneType] ([IsActive],[IsInactiveViewable],[LaneTypeName]) VALUES
        (1, 1, 'All'), 
        (1, 1, 'Total Profitable'), 
        (1, 1, 'Total Non-Profitable'),
        (1, 1, 'Catch-all Profitable'),
        (1, 1, 'Catch-all Non-Profitable')
        """
    cursor_update.execute(sql_insert)


class Migration(migrations.Migration):
    dependencies = [
        ('rrf', '0098_auto_20220705_1200')
    ]

    operations = [
        migrations.RunPython(insert_lane_type_data)
    ]
