# Generated by Django 2.1.13 on 2022-07-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0099_auto_20220705_1842'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessorialoverride',
            unique_together={('request_id', 'acc_header_id', 'origin_id', 'origin_type_id', 'destination_id', 'destination_type_id', 'request_section_id')},
        ),
    ]
