# Generated by Django 2.1.13 on 2022-07-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0100_auto_20220708_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='request_id',
            field=models.ForeignKey(db_column='RequestID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Request', unique=True),
        ),
    ]
