# Generated by Django 2.1.13 on 2022-07-11 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20220510_1629'),
        ('rrf', '0101_auto_20220708_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='carrier_status',
            field=models.TextField(db_column='CarrierStatus', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='cost_plus_status',
            field=models.TextField(db_column='CostPlusStatus', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='credit_analyst',
            field=models.ForeignKey(db_column='CreditAnalystID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='current_editor',
            field=models.ForeignKey(db_column='CurrentEditorID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='pricing_analyst',
            field=models.ForeignKey(db_column='PricingAnalystID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='pricing_assigned',
            field=models.DateTimeField(db_column='PricingAssigned', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='pricing_opened',
            field=models.DateTimeField(db_column='PricingOpened', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='pricing_running',
            field=models.BooleanField(db_column='PricingRunning', default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='sales_representative',
            field=models.ForeignKey(db_column='SalesRepresentativeID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='sales_status',
            field=models.TextField(db_column='SalesStatus', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='carrier_status',
            field=models.TextField(db_column='CarrierStatus', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='cost_plus_status',
            field=models.TextField(db_column='CostPlusStatus', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='credit_analyst_version',
            field=models.ForeignKey(db_column='CreditAnalystVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.UserHistory'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='current_editor_version',
            field=models.ForeignKey(db_column='CurrentEditorVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.UserHistory'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='pricing_analyst_version',
            field=models.ForeignKey(db_column='PricingAnalystVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.UserHistory'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='pricing_assigned',
            field=models.DateTimeField(db_column='PricingAssigned', null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='pricing_opened',
            field=models.DateTimeField(db_column='PricingOpened', null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='pricing_running',
            field=models.BooleanField(db_column='PricingRunning', default=0),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='sales_representative_version',
            field=models.ForeignKey(db_column='SalesRepresentativeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.UserHistory'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='sales_status',
            field=models.TextField(db_column='SalesStatus', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='request_id',
            field=models.OneToOneField(db_column='RequestID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.Request'),
        ),
    ]
