# Generated by Django 2.1.13 on 2022-07-11 17:07

from django.db import migrations, connection


# Method to insert values in SalesIncentive
def insert_sales_incentive_data(apps, schema_editor):
    cursor_update = connection.cursor()
    sql_insert = """
        INSERT INTO [dbo].[SalesIncentive] ([IsActive],[IsInactiveViewable],[SalesIncentiveType]) VALUES
        (1, 1, 'Increase'), 
        (1, 1, 'Legacy Account'), 
        (1, 1, 'Negotiate'),
        (1, 1, 'Decrease'),
        (1, 1, 'Hold'),
        (1, 1, 'Redo'),
        (1, 1, 'Cancel')
        """
    cursor_update.execute(sql_insert)


class Migration(migrations.Migration):
    dependencies = [
        ('rrf', '0102_auto_20220711_1344'),
    ]

    operations = [
        migrations.RunPython(insert_sales_incentive_data)
    ]
