# Generated by Django 2.1.13 on 2022-07-16 14:05

from django.db import migrations,connection

def update_request_statuses(apps, schema_editor):
    cursor_update = connection.cursor()
    sql_insert = """
        SET IDENTITY_INSERT dbo.RequestStatusType ON;
        MERGE INTO dbo.RequestStatusType AS tgt
        USING (VALUES
                ( 1, 1, 'Initiated', 1),
                ( 1, 1, 'With Pricing', 2),
                ( 1, 1, 'Cost+ Analysis', 3),
                ( 1, 1, 'With Partner Carrier', 4),
                ( 1, 1, 'Sales Review', 5),
                ( 1, 1, 'Publish Queued', 6),
                ( 1, 1, 'Ready for Publish', 7),
                ( 1, 1, 'Published', 8),
                ( 1, 1, 'Declined', 9),
                ( 1, 1, 'Annual Review', 10),
                ( 1, 1, 'In Review Approval', 11),
                ( 1, 1, 'Credit Analysis', 12),
                ( 1, 1, 'Archived', 13),
                ( 1, 1, 'Spot Quote', 14),
                ( 1, 1, 'Approve for Publishing', 15)
                )
               as src (IsActive, IsInactiveViewable, RequestStatusTypeName, RequestStatusTypeID)
        ON tgt.RequestStatusTypeID = src.RequestStatusTypeID
        WHEN MATCHED THEN
        UPDATE SET RequestStatusTypeName = src.RequestStatusTypeName
        WHEN NOT MATCHED THEN
            INSERT (IsActive, IsInactiveViewable, RequestStatusTypeName, RequestStatusTypeID)
            VALUES (src.IsActive, src.IsInactiveViewable, src.RequestStatusTypeName, src.RequestStatusTypeID)
            ;
        SET IDENTITY_INSERT dbo.RequestStatusType OFF;
        """

    cursor_update.execute(sql_insert)
class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0105_auto_20220716_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requeststatustype',
            name='assigned_persona',
        ),
        migrations.RemoveField(
            model_name='requeststatustype',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='requeststatustype',
            name='is_final',
        ),
        migrations.RemoveField(
            model_name='requeststatustype',
            name='is_secondary',
        ),
        migrations.RemoveField(
            model_name='requeststatustype',
            name='next_request_status_type',
        ),
        migrations.RemoveField(
            model_name='requeststatustype',
            name='queue_personas',
        ),
        migrations.RemoveField(
            model_name='requeststatustypehistory',
            name='assigned_persona',
        ),
        migrations.RemoveField(
            model_name='requeststatustypehistory',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='requeststatustypehistory',
            name='is_final',
        ),
        migrations.RemoveField(
            model_name='requeststatustypehistory',
            name='is_secondary',
        ),
        migrations.RemoveField(
            model_name='requeststatustypehistory',
            name='next_request_status_type',
        ),
        migrations.RemoveField(
            model_name='requeststatustypehistory',
            name='queue_personas',
        ),
        migrations.RunPython(update_request_statuses),
    ]
