# Generated by Django 2.1.13 on 2022-07-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0107_auto_20220716_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requeststatus',
            name='credit_analyst',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='current_editor',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='pricing_analyst',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='request',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='request_status_type',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='sales_representative',
        ),
        migrations.AlterIndexTogether(
            name='requeststatushistory',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='requeststatushistory',
            name='credit_analyst_version',
        ),
        migrations.RemoveField(
            model_name='requeststatushistory',
            name='current_editor_version',
        ),
        migrations.RemoveField(
            model_name='requeststatushistory',
            name='pricing_analyst_version',
        ),
        migrations.RemoveField(
            model_name='requeststatushistory',
            name='request_status',
        ),
        migrations.RemoveField(
            model_name='requeststatushistory',
            name='request_status_type_version',
        ),
        migrations.RemoveField(
            model_name='requeststatushistory',
            name='request_version',
        ),
        migrations.RemoveField(
            model_name='requeststatushistory',
            name='sales_representative_version',
        ),
        migrations.DeleteModel(
            name='RequestStatus',
        ),
        migrations.DeleteModel(
            name='RequestStatusHistory',
        ),
    ]
