# Generated by Django 2.1.13 on 2022-07-17 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220510_1629'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrf', '0108_auto_20220716_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approver',
            field=models.ForeignKey(blank=True, db_column='ApproverID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='approver_version',
            field=models.ForeignKey(blank=True, db_column='ApproverVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.UserHistory'),
        ),
    ]
