# Generated by Django 2.1.13 on 2022-08-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0109_auto_20220716_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='equipment_type_code',
            field=models.CharField(db_column='EquipmentTypeCode', max_length=10),
        ),
    ]
