# Generated by Django 2.1.13 on 2022-08-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0110_auto_20220802_2344'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmenttype',
            unique_together={('equipment_type_name', 'equipment_type_code')},
        ),
    ]
