# Generated by Django 2.1.13 on 2022-08-04 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0111_auto_20220803_0907'),
    ]

    operations = [
#         migrations.AlterIndexTogether(
#             name='requestaccessorialshistory',
#             index_together=set(),
#         ),
        migrations.RemoveField(
            model_name='requestaccessorialshistory',
            name='request_accessorials',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_accessorials',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_information',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_lane',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_profile',
        ),
        migrations.RemoveField(
            model_name='requesthistory',
            name='request_accessorials_version',
        ),
        migrations.RemoveField(
            model_name='requesthistory',
            name='request_information_version',
        ),
        migrations.RemoveField(
            model_name='requesthistory',
            name='request_lane_version',
        ),
        migrations.RemoveField(
            model_name='requesthistory',
            name='request_profile_version',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='request_number',
        ),
        migrations.RemoveField(
            model_name='tariffhistory',
            name='request_number',
        ),
        migrations.AddField(
            model_name='requestinformation',
            name='request_id',
            field=models.ForeignKey(db_column='RequestID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.Request'),
        ),
        migrations.AddField(
            model_name='requestinformationhistory',
            name='request_version_id',
            field=models.ForeignKey(db_column='RequestVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.RequestHistory'),
        ),
        migrations.AddField(
            model_name='requestprofile',
            name='request_id',
            field=models.ForeignKey(db_column='RequestID', default=3, on_delete=django.db.models.deletion.CASCADE, to='rrf.Request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestprofilehistory',
            name='request_id',
            field=models.ForeignKey(db_column='RequestVersionID', default=3, on_delete=django.db.models.deletion.CASCADE, to='rrf.RequestHistory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RequestAccessorialsHistory',
        ),
        migrations.DeleteModel(
            name='RequestAccessorials',
        ),

    ]
