# Generated by Django 2.1.13 on 2022-08-04 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0115_auto_20220804_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(db_column='CommentID', primary_key=True, serialize=False)),
                ('request_major_version', models.IntegerField(db_column='RequestMajorVersion', default=1)),
                ('tag', models.CharField(db_column='Tag', max_length=100, null=True)),
                ('status', models.CharField(db_column='Status', default='ACTIVE', max_length=25, null=True)),
                ('type', models.CharField(db_column='Type', max_length=25, null=True)),
                ('content', models.TextField(db_column='Content')),
                ('parent_comment_id', models.BigIntegerField(blank=True, db_column='ParentCommentID', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('created_by', models.CharField(db_column='CreatedBy', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='request_major_version',
            field=models.IntegerField(db_column='RequestMajorVersion', default=1),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='request_major_version',
            field=models.IntegerField(db_column='RequestMajorVersion', default=1),
        ),
        migrations.AddField(
            model_name='comment',
            name='request_id',
            field=models.ForeignKey(db_column='RequestID', on_delete=django.db.models.deletion.CASCADE, to='rrf.Request'),
        ),
    ]
