# Generated by Django 2.1.13 on 2022-08-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0117_auto_20220804_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='new_lanes_only',
            field=models.BooleanField(db_column='NewLanesOnly', default=False),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='new_lanes_only',
            field=models.BooleanField(db_column='NewLanesOnly', default=False),
        ),
    ]
