# Generated by Django 2.1.13 on 2022-08-04 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0121_auto_20220804_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='acc_rate_factor_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='acc_rate_range_type_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='destination_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='free_time_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='max_shipment_value',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='max_weight_value',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='min_shipment_value',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='min_weight_value',
        ),
        migrations.RemoveField(
            model_name='accessorialdetail',
            name='origin_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='acc_rate_factor_version_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='destination_type',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='free_time_version_id',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='max_shipment_value',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='max_weight_value',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='min_shipment_value',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='min_weight_value',
        ),
        migrations.RemoveField(
            model_name='accessorialdetailhistory',
            name='origin_type',
        ),
        migrations.RemoveField(
            model_name='accessorialheader',
            name='dangerous_goods',
        ),
        migrations.RemoveField(
            model_name='accessorialheader',
            name='temperature_controlled',
        ),
        migrations.RemoveField(
            model_name='accessorialheaderhistory',
            name='dangerous_goods',
        ),
        migrations.RemoveField(
            model_name='accessorialheaderhistory',
            name='temperature_controlled',
        ),
        migrations.RemoveField(
            model_name='freetime',
            name='calc_order',
        ),
        migrations.RemoveField(
            model_name='freetime',
            name='rate_unit',
        ),
        migrations.RemoveField(
            model_name='freetime',
            name='tm_range_type_code',
        ),
        migrations.RemoveField(
            model_name='freetimehistory',
            name='calc_order',
        ),
        migrations.RemoveField(
            model_name='freetimehistory',
            name='rate_unit',
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='acc_max',
            field=models.DecimalField(db_column='AccMax', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='acc_min',
            field=models.DecimalField(db_column='AccMin', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='acc_percent',
            field=models.DecimalField(db_column='AccPercent', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='acc_rate_factor',
            field=models.DecimalField(db_column='AccRateFactor', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='acc_rate_range_field1_from',
            field=models.DecimalField(db_column='AccRateRangeField1From', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='acc_rate_range_field1_to',
            field=models.DecimalField(db_column='AccRateRangeField1To', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='acc_rate_range_field2ID',
            field=models.DecimalField(db_column='AccRateRangeField2ID', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='acc_rate_range_field2_from',
            field=models.DecimalField(db_column='AccRateRangeField2From', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='acc_rate_range_field2_to',
            field=models.DecimalField(db_column='AccRateRangeField2To', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetail',
            name='service_type',
            field=models.ForeignKey(db_column='ServiceTypeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.ServiceType'),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='acc_max',
            field=models.DecimalField(db_column='AccMax', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='acc_min',
            field=models.DecimalField(db_column='AccMin', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='acc_percent',
            field=models.DecimalField(db_column='AccPercent', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='acc_rate_factor',
            field=models.DecimalField(db_column='AccRateFactor', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='acc_rate_range_field1_from',
            field=models.DecimalField(db_column='AccRateRangeField1From', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='acc_rate_range_field1_to',
            field=models.DecimalField(db_column='AccRateRangeField1To', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='acc_rate_range_field2ID',
            field=models.DecimalField(db_column='AccRateRangeField2ID', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='acc_rate_range_field2_from',
            field=models.DecimalField(db_column='AccRateRangeField2From', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='acc_rate_range_field2_to',
            field=models.DecimalField(db_column='AccRateRangeField2To', decimal_places=6, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='service_type_version',
            field=models.ForeignKey(db_column='ServiceTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.ServiceTypeHistory'),
        ),
        migrations.AddField(
            model_name='accessorialdetention',
            name='calc_order',
            field=models.BigIntegerField(db_column='CalcOrder', default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetention',
            name='rate_unit',
            field=models.TextField(db_column='RateUnit', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetentionhistory',
            name='calc_order',
            field=models.BigIntegerField(db_column='CalcOrder', default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetentionhistory',
            name='rate_unit',
            field=models.TextField(db_column='RateUnit', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialstorage',
            name='calc_order',
            field=models.BigIntegerField(db_column='CalcOrder', default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessorialstorage',
            name='rate_unit',
            field=models.TextField(db_column='RateUnit', default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessorialstoragehistory',
            name='calc_order',
            field=models.BigIntegerField(db_column='CalcOrder', default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessorialstoragehistory',
            name='rate_unit',
            field=models.TextField(db_column='RateUnit', default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='freetime',
            name='free_time',
            field=models.IntegerField(db_column='FreeTime', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='freetimehistory',
            name='free_time',
            field=models.IntegerField(db_column='FreeTime', default=None, null=True),
        ),
    ]
