# Generated by Django 2.1.13 on 2022-08-10 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0118_auto_20220805_1153'),
        ('rrf', '0122_auto_20220804_1749'),
    ]

    operations = [
    ]
