# Generated by Django 2.1.13 on 2022-08-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0123_merge_20220809_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='type',
        ),
        migrations.AddField(
            model_name='comment',
            name='request_status_type_id',
            field=models.ForeignKey(db_column='RequestStatusTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.RequestStatusType'),
        ),
    ]
