# Generated by Django 2.1.13 on 2022-08-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0124_auto_20220809_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
