# Generated by Django 2.1.13 on 2022-08-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0125_remove_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(db_column='IsActive', default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_inactive_viewable',
            field=models.BooleanField(db_column='IsInactiveViewable', default=True),
        ),
    ]
