# Generated by Django 2.1.13 on 2022-08-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0126_auto_20220809_1600'),
        ('rrf', '0123_merge_20220809_2116'),
    ]

    operations = [
    ]
