# Generated by Django 2.1.13 on 2022-08-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0128_freightbillwarning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessorialstorage',
            name='rate_unit',
        ),
        migrations.RemoveField(
            model_name='accessorialstoragehistory',
            name='rate_unit',
        ),
        migrations.AlterField(
            model_name='accessorialdetail',
            name='tmacc_detail_id',
            field=models.TextField(db_column='TMAccDetailID', default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetailhistory',
            name='tmacc_detail_id',
            field=models.TextField(db_column='TMAccDetailID', default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='accessorialdetention',
            name='sub_service_level_id',
            field=models.ForeignKey(db_column='SubServiceLevelID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.SubServiceLevel'),
        ),
        migrations.AlterField(
            model_name='accessorialdetentionhistory',
            name='sub_service_level_version_id',
            field=models.ForeignKey(db_column='SubServiceLevelVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevelHistory'),
        ),
        migrations.AlterField(
            model_name='accessorialstorage',
            name='sub_service_level_id',
            field=models.ForeignKey(db_column='SubServiceLevelID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevel'),
        ),
        migrations.AlterField(
            model_name='accessorialstoragehistory',
            name='sub_service_level_version_id',
            field=models.ForeignKey(db_column='SubServiceLevelVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevelHistory'),
        ),
    ]
