# Generated by Django 2.1.13 on 2022-08-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0129_auto_20220815_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorialheader',
            name='acc_range_field_id',
            field=models.ForeignKey(db_column='AccRangeFieldID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccRangeType'),
        ),
    ]
