# Generated by Django 2.1.13 on 2022-09-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0127_merge_20220811_1053'),
        ('rrf', '0130_auto_20220825_0951'),
    ]

    operations = [
    ]
