# Generated by Django 2.1.13 on 2022-09-07 14:47

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0131_merge_20220907_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestprofile',
            old_name='using_standard_tarrif',
            new_name='using_standard_tariff',
        ),
    ]
