# Generated by Django 2.1.13 on 2022-09-07 14:47

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0131_merge_20220907_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorialdetailhistory',
            name='acc_header_version_id',
            field=models.ForeignKey(db_column='AccHeaderVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
            to='rrf.AccessorialHeaderHistory'),
        ),
    ]
