# Generated by Django 2.1.13 on 2022-09-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0133_acc_history_fix'),
        ('rrf', '0132_auto_20220907_1147'),
    ]

    operations = [
    ]
