# Generated by Django 2.1.13 on 2022-09-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0136_auto_20220907_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorialdetailhistory',
            name='acc_header_version_id',
            field=models.ForeignKey(db_column='AccHeaderVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccessorialHeaderHistory'),
        ),
    ]
