# Generated by Django 2.1.13 on 2022-09-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0137_auto_20220907_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorialdetailhistory',
            name='acc_range_type_version_id',
            field=models.ForeignKey(db_column='AccRangeTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccRangeTypeHistory'),
        ),
    ]
