# Generated by Django 2.1.13 on 2022-09-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0138_auto_20220907_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorialheaderhistory',
            name='acc_range_field_version_id',
            field=models.ForeignKey(db_column='AccRangeFieldVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccRangeTypeHistory'),
        ),
        migrations.AlterField(
            model_name='accessorialheaderhistory',
            name='business_grouping',
            field=models.BigIntegerField(db_column='BusinessGrouping', default=None, null=True),
        ),
    ]
