# Generated by Django 2.1.13 on 2022-09-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0032_merge_20220907_1147'),
        ('rrf', '0140_auto_20220907_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceclassmap',
            name='service_level',
        ),
        migrations.RemoveField(
            model_name='serviceclassmaphistory',
            name='service_level_version',
        ),
        migrations.AddField(
            model_name='serviceclassmap',
            name='sub_service_level',
            field=models.ForeignKey(db_column='SubServiceLevelID', default=8, on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevel'),
        ),
        migrations.AddField(
            model_name='serviceclassmaphistory',
            name='sub_service_level_version',
            field=models.ForeignKey(db_column='SubServiceLevelVersionID', default=8, on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevelHistory'),
        ),
    ]
