# Generated by Django 2.1.13 on 2022-09-07 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0142_auto_20220907_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorialdetailhistory',
            name='sub_service_level_version_id',
            field=models.ForeignKey(db_column='SubServiceLevelVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.SubServiceLevelHistory'),
        ),
    ]
