# Generated by Django 2.1.13 on 2022-09-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0143_auto_20220907_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestprofilehistory',
            name='using_standard_tarrif',
        ),
        migrations.AddField(
            model_name='requestprofilehistory',
            name='using_standard_tariff',
            field=models.BooleanField(db_column='UsingStandardTariff', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_eff_date',
            field=models.DateTimeField(db_column='ReviewEffDate', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_exp_date',
            field=models.DateTimeField(db_column='ReviewExpDate', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewhistory',
            name='review_eff_date',
            field=models.DateTimeField(db_column='ReviewEffDate', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewhistory',
            name='review_exp_date',
            field=models.DateTimeField(db_column='ReviewExpDate', default=None, null=True),
        ),
    ]
