# Generated by Django 2.1.13 on 2022-09-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0143_auto_20220907_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorialdetail',
            name='acc_rate_range_field1ID',
            field=models.ForeignKey(db_column='AccRateRangeField1ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.AccRangeType'),
        ),
    ]
