# Generated by Django 2.1.13 on 2022-09-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0144_auto_20220908_1111'),
    ]

    operations = [
#         migrations.RenameField(
#             model_name='requestprofilehistory',
#             old_name='using_standard_tarrif',
#             new_name='using_standard_tariff',
#         ),
    ]
