# Generated by Django 2.1.13 on 2022-09-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0145_auto_20220909_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interlinercosts',
            name='equipment_type_id',
            field=models.ForeignKey(db_column='EquipmentTypeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.EquipmentType'),
        ),
        migrations.AlterField(
            model_name='interlinercostshistory',
            name='equipment_type_version_id',
            field=models.ForeignKey(db_column='EquipmentTypeVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.EquipmentTypeHistory'),
        ),
    ]
