# Generated by Django 2.1.13 on 2022-09-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0144_auto_20220912_1015'),
        ('rrf', '0146_auto_20220912_1153'),
    ]

    operations = [
    ]
