# Generated by Django 2.1.13 on 2022-09-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0147_merge_20220921_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorialdetentionoverride',
            name='tmid',
            field=models.IntegerField(db_column='TMID', default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessorialdetentionoverridehistory',
            name='tmid',
            field=models.IntegerField(db_column='TMID', default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverride',
            name='tmid',
            field=models.IntegerField(db_column='TMID', default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessorialoverridehistory',
            name='tmid',
            field=models.IntegerField(db_column='TMID', default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessorialstorageoverride',
            name='tmid',
            field=models.IntegerField(db_column='TMID', default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessorialstorageoverridehistory',
            name='tmid',
            field=models.IntegerField(db_column='TMID', default=None, null=True),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='tmid',
            field=models.IntegerField(db_column='TMID', default=None, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionhistory',
            name='tmid',
            field=models.IntegerField(db_column='TMID', default=None, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlane',
            name='tmid',
            field=models.IntegerField(db_column='TMID', default=None, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='tmid',
            field=models.IntegerField(db_column='TMID', default=None, null=True),
        ),
    ]
