# Generated by Django 2.1.13 on 2022-09-22 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0035_auto_20220922_1427'),
        ('rrf', '0148_auto_20220921_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='service_point',
            field=models.ForeignKey(db_column='ServicePointID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.ServicePoint'),
        ),
        migrations.AddField(
            model_name='customerhistory',
            name='service_point_version',
            field=models.ForeignKey(db_column='ServicePointVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.ServicePointHistory'),
        ),
    ]
