# Generated by Django 2.1.13 on 2020-09-15 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pac', '__first__'),
    ]

    operations = [


    ]
