# Generated by Django 2.1.13 on 2022-04-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_costing', '0014_auto_20220324_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokercontractcost',
            name='pickup_delivery_count',
            field=models.IntegerField(blank=True, db_column='PickupDeliveryCount', default=0, null=True),
        ),
    ]
