# Generated by Django 2.1.13 on 2022-04-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_costing', '0016_auto_20220412_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokercontractcosthistory',
            name='pickup_delivery_count',
            field=models.IntegerField(blank=True, db_column='PickupDeliveryCount', default=0, null=True),
        ),
        migrations.AddField(
            model_name='brokercontractcosthistory',
            name='rate_base',
            field=models.DecimalField(blank=True, db_column='RateBase', decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='brokercontractcosthistory',
            name='rate_max',
            field=models.DecimalField(blank=True, db_column='RateMax', decimal_places=6, max_digits=19, null=True),
        ),
    ]
