# Generated by Django 2.1.13 on 2022-04-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0013_auto_20220412_1423'),
        ('pre_costing', '0017_auto_20220412_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotQuoteMargin',
            fields=[
                ('is_active', models.BooleanField(db_column='IsActive', default=1)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=1)),
                ('spot_quote_margin_id', models.BigAutoField(db_column='SpotQuoteMarginID', primary_key=True, serialize=False)),
                ('min_margin', models.CharField(db_column='MinMargin', max_length=40)),
                ('std_margin', models.CharField(db_column='StdMargin', max_length=40)),
                ('max_margin', models.CharField(db_column='MaxMargin', max_length=40)),
                ('destination_province_id', models.ForeignKey(db_column='DestinationProvinceID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.Province')),
                ('origin_province_id', models.ForeignKey(db_column='OriginProvinceID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.Province')),
                ('sub_service_level_id', models.ForeignKey(db_column='SubServiceLevelID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevel')),
            ],
            options={
                'db_table': 'SpotQuoteMargin',
            },
        ),
        migrations.CreateModel(
            name='SpotQuoteMarginHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=1)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, db_column='UpdatedOn')),
                ('updated_by', models.CharField(db_column='UpdatedBy', default='', max_length=50)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None, null=True)),
                ('comments', models.CharField(db_column='Comments', default='', max_length=4000)),
                ('is_active', models.BooleanField(db_column='IsActive', default=1)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=1)),
                ('spot_quote_margin_version_id', models.BigAutoField(db_column='SpotQuoteMarginVersionID', primary_key=True, serialize=False)),
                ('min_margin', models.CharField(db_column='MinMargin', max_length=40)),
                ('std_margin', models.CharField(db_column='StdMargin', max_length=40)),
                ('max_margin', models.CharField(db_column='MaxMargin', max_length=40)),
                ('destination_province_version_id', models.ForeignKey(db_column='DestinationProvinceVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.ProvinceHistory')),
                ('origin_province_version_id', models.ForeignKey(db_column='OriginProvinceVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.ProvinceHistory')),
                ('spot_quote_margin_id', models.ForeignKey(db_column='SpotQuoteMarginID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pre_costing.SpotQuoteMargin')),
                ('sub_service_level_version_id', models.ForeignKey(db_column='SubServiceLevelVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevelHistory')),
            ],
            options={
                'db_table': 'SpotQuoteMarginHistory',
            },
        ),
        migrations.AlterIndexTogether(
            name='spotquotemarginhistory',
            index_together={('spot_quote_margin_id', 'version_num')},
        ),
    ]
