# Generated by Django 2.1.13 on 2022-04-21 16:50

from django.db import migrations, connection

# Method to insert values in SpotQuoteMargin
def insert_spotquote_margin_data(apps, schema_editor):
    cursor_update = connection.cursor()
    sql_insert = """
        INSERT INTO  [dbo].[SpotQuoteMargin] 
		([IsActive],[IsInactiveViewable],[OriginProvinceID],[DestinationProvinceID],
		[ServiceLevelID], [MinMargin],[StdMargin],[MaxMargin]) VALUES
        (1, 1, 6, 3, 84, 67, 70, 85), 
        (1, 1, 3, 6, 88, 57, 65, 76), 
        (1, 1, 46, 50, 89, 45, 60, 70), 
		(1, 1, 49, 50, 90, 50, 55, 65);
        """
    cursor_update.execute(sql_insert)

class Migration(migrations.Migration):

    dependencies = [
        ('pre_costing', '0018_auto_20220421_1327'),
    ]

    operations = [
        migrations.RunPython(insert_spotquote_margin_data),
    ]

