# Generated by Django 2.1.13 on 2022-04-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_costing', '0019_auto_20220421_1350'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spotquotemarginhistory',
            table='SpotQuoteMargin_History',
        ),
    ]
