# Generated by Django 2.1.13 on 2022-08-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_costing', '0023_auto_20220715_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokercontractcost',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='brokercontractcosthistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='lane',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='lanecost',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='lanecosthistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='lanehistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='laneroute',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='laneroutehistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='legcost',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='legcosthistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='terminalcost',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='terminalcosthistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='terminalservicepoint',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='terminalservicepointhistory',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_column='LegacyID', null=True),
        ),
    ]
