# Generated by Django 2.1.13 on 2022-09-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_costing', '0024_auto_20220811_1145'),
        ('pre_costing', '0025_auto_20220811_1057'),
    ]

    operations = [
    ]
